# Pre-registered mutation battery rows for the full-sync/PSYNC handoff model.
# Authored in full BEFORE any mutation was run. `expected` is the prediction.
LOGIC = "specs/quint/replication_fullsync_logic.qnt"
MACH = "specs/quint/replication_fullsync_machine.qnt"
TYPES = "specs/quint/replication_fullsync_types.qnt"
MAIN = "specs/quint/replication_fullsync.qnt"

ROWS = [
    # ---------------- logic: windowContains (TR-001 / FM-013 / FM-019) ----------------
    dict(
        id="F01",
        f=LOGIC,
        loc="windowContains d1 — the primary arm needs an offset the primary reached",
        old="      p.replid == id and off <= p.recv,",
        new="      p.replid == id,",
        exp="inv_no_acked_write_lost_across_fullsync (grant past the primary's head)",
    ),
    dict(
        id="F02",
        f=LOGIC,
        loc="windowContains d1 — the primary arm needs id equality",
        old="      p.replid == id and off <= p.recv,",
        new="      off <= p.recv,",
        exp="inv_no_acked_write_lost_across_fullsync (foreign history granted)",
    ),
    dict(
        id="F03",
        f=LOGIC,
        loc="windowContains d2 c1 — the secondary arm needs the inherited id",
        old="        optExists(p.replid2, g => g == id),",
        new="        true,",
        exp="inv_no_acked_write_lost_across_fullsync / inv_splice_continuity",
    ),
    dict(
        id="F04",
        f=LOGIC,
        loc="windowContains d2 c2 — the window must be present",
        old="        p.second_offset != NO_WINDOW,\n        off <= p.second_offset,",
        new="        off <= p.second_offset,",
        exp="(pre-registered miss) redundant with inv_failover_window_whole",
    ),
    dict(
        id="F05",
        f=LOGIC,
        loc="windowContains d2 c3 — the boundary is the frozen offset, not the live head",
        old="        off <= p.second_offset,",
        new="        off <= p.recv,",
        exp="inv_no_acked_write_lost_across_fullsync (resume past the frozen window)",
    ),
    dict(
        id="F06",
        f=LOGIC,
        loc="windowContains d2 c3 — the frozen boundary is inclusive (no Redis +1)",
        old="        off <= p.second_offset,",
        new="        off < p.second_offset,",
        exp="partialResyncViaReplid2WindowTest / overshippedTailMeetsFailoverTest",
    ),
    # ---------------- logic: floorAdmits (FM-014) ----------------
    dict(
        id="F07",
        f=LOGIC,
        loc="floorAdmits c1 — an unarmed floor always refuses",
        old="    p.floor != UNARMED and off >= p.floor",
        new="    off >= p.floor",
        exp="(pre-registered miss) no test forces a refusal against an unarmed floor",
    ),
    dict(
        id="F08",
        f=LOGIC,
        loc="floorAdmits c2 — the resumable side is inclusive (req == floor continues)",
        old="    p.floor != UNARMED and off >= p.floor",
        new="    p.floor != UNARMED and off > p.floor",
        exp="(pre-registered miss) no test resumes at exactly the floor",
    ),
    # ---------------- logic: decideArm (FM-013) ----------------
    dict(
        id="F09",
        f=LOGIC,
        loc="decideArm arm1 — a replica with no history always full-syncs",
        old="    if (r.replid == NO_HISTORY) FullSnapshot",
        new="    if (false) FullSnapshot",
        exp="(pre-registered miss) equivalent: no primary ever heads NO_HISTORY",
    ),
    dict(
        id="F10",
        f=LOGIC,
        loc="decideArm arm1 — inverted: no history gets +CONTINUE",
        old="    if (r.replid == NO_HISTORY) FullSnapshot\n    else if (not(windowContains(p, r.replid, r.applied))) FullSnapshot",
        new="    if (r.replid == NO_HISTORY) PartialGrant\n    else if (not(windowContains(p, r.replid, r.applied))) FullSnapshot",
        exp="happyFullSyncTest + inv_partial_grant_sound (grantForeignHistory)",
    ),
    dict(
        id="F11",
        f=LOGIC,
        loc="decideArm arm2 — the window is checked at the applied offset",
        old="    else if (not(windowContains(p, r.replid, r.applied))) FullSnapshot",
        new="    else if (not(windowContains(p, r.replid, r.recv))) FullSnapshot",
        exp="inv_partial_grant_sound (grantForeignHistory ghost recomputes from applied)",
    ),
    dict(
        id="F12",
        f=LOGIC,
        loc="decideArm arm3 — the floor is checked at the applied offset",
        old="    else if (not(floorAdmits(p, r.applied))) FullSnapshot",
        new="    else if (not(floorAdmits(p, r.recv))) FullSnapshot",
        exp="inv_partial_grant_sound (grantBelowFloor ghost recomputes from applied)",
    ),
    dict(
        id="F13",
        f=LOGIC,
        loc="decideArm tail — a satisfied window+floor grants +CONTINUE",
        old="    else PartialGrant",
        new="    else FullSnapshot",
        exp="partialResyncViaReplid2WindowTest, spliceOverEvictedRangeFailsTest",
    ),
    # ---------------- logic: degradedByFloor / grantedViaSecondary (coverage ghosts) ----------------
    dict(
        id="F14",
        f=LOGIC,
        loc="degradedByFloor c2 — only a floor-caused degradation counts",
        old="      windowContains(p, r.replid, r.applied),\n      not(floorAdmits(p, r.applied)),",
        new="      not(floorAdmits(p, r.applied)),",
        exp="(pre-registered miss) coverage over-latch, no negative assertion",
    ),
    dict(
        id="F15",
        f=LOGIC,
        loc="degradedByFloor c3 — the floor is what refused",
        old="      not(floorAdmits(p, r.applied)),\n    }",
        new="      floorAdmits(p, r.applied),\n    }",
        exp="backlogEvictionForcesFullResyncTest (coverage.evictionForcedFull)",
    ),
    dict(
        id="F16",
        f=LOGIC,
        loc="grantedViaSecondary c1 — the ids must actually differ",
        old="    p.replid != r.replid and optExists(p.replid2, g => g == r.replid)",
        new="    optExists(p.replid2, g => g == r.replid)",
        exp="(pre-registered miss) equivalent: coupled to inv_replids_distinct",
    ),
    dict(
        id="F17",
        f=LOGIC,
        loc="grantedViaSecondary c2 — served out of the inherited window",
        old="    p.replid != r.replid and optExists(p.replid2, g => g == r.replid)",
        new="    p.replid != r.replid",
        exp="(pre-registered miss) coverage over-latch, no negative assertion",
    ),
    # ---------------- logic: applyWriteOnPrimary (TR-030) ----------------
    dict(
        id="F18",
        f=LOGIC,
        loc="applyWriteOnPrimary — the write lands in the dataset",
        old="    data: p.data.append(w),",
        new="    data: p.data,",
        exp="happyFullSyncTest + inv_applied_covered_by_data",
    ),
    dict(
        id="F19",
        f=LOGIC,
        loc="applyWriteOnPrimary — the write advances the live head",
        old="    recv: p.recv + 1,",
        new="    recv: p.recv,",
        exp="inv_offsets_ordered + happyFullSyncTest",
    ),
    dict(
        id="F20",
        f=LOGIC,
        loc="applyWriteOnPrimary — the write advances the applied offset",
        old="    applied: p.applied + 1,",
        new="    applied: p.applied,",
        exp="inv_identity_pair_monotone (a restart then rewinds at a fixed gen)",
    ),
    dict(
        id="F21",
        f=LOGIC,
        loc="applyWriteOnPrimary — the floor is armed once, at the first push",
        old="    floor: if (p.floor == UNARMED) p.recv else p.floor,",
        new="    floor: p.recv,",
        exp="backlogEvictionForcesFullResyncTest (evict guard starves)",
    ),
    dict(
        id="F22",
        f=LOGIC,
        loc="applyWriteOnPrimary — the floor opens at the command's start offset",
        old="    floor: if (p.floor == UNARMED) p.recv else p.floor,",
        new="    floor: if (p.floor == UNARMED) p.recv + 1 else p.floor,",
        exp="backlogEvictionForcesFullResyncTest (floor == 2 check)",
    ),
    # ---------------- logic: backlog eviction (FM-016) ----------------
    dict(
        id="F23",
        f=LOGIC,
        loc="canEvictBacklog c1 — only a primary evicts",
        old="    p.role == Primary and p.floor != UNARMED and p.recv - p.floor > BACKLOG_CAP",
        new="    p.floor != UNARMED and p.recv - p.floor > BACKLOG_CAP",
        exp="(pre-registered miss) equivalent: only primaries ever arm a floor",
    ),
    dict(
        id="F24",
        f=LOGIC,
        loc="canEvictBacklog c2 — an unarmed buffer has nothing to evict",
        old="    p.role == Primary and p.floor != UNARMED and p.recv - p.floor > BACKLOG_CAP",
        new="    p.role == Primary and p.recv - p.floor > BACKLOG_CAP",
        exp="(pre-registered miss) arms a floor no push opened; model never discards data",
    ),
    dict(
        id="F25",
        f=LOGIC,
        loc="canEvictBacklog c3 — eviction only above capacity",
        old="    p.role == Primary and p.floor != UNARMED and p.recv - p.floor > BACKLOG_CAP",
        new="    p.role == Primary and p.floor != UNARMED and p.recv - p.floor >= BACKLOG_CAP",
        exp="(pre-registered miss) over-eviction only forces safe full resyncs",
    ),
    dict(
        id="F26",
        f=LOGIC,
        loc="applyEvictBacklog — the floor rises to the evicted entry's end",
        old="    { ...p, floor: p.floor + 1 }",
        new="    { ...p, floor: p.floor + 2 }",
        exp="backlogEvictionForcesFullResyncTest (floor == 2 check)",
    ),
    dict(
        id="F27",
        f=LOGIC,
        loc="applyEvictBacklog — FIFO, not whole-buffer discard",
        old="    { ...p, floor: p.floor + 1 }",
        new="    { ...p, floor: p.recv }",
        exp="backlogEvictionForcesFullResyncTest (floor == 2 check)",
    ),
    # ---------------- logic: checkpoint cut (TR-003 / FM-004) ----------------
    dict(
        id="F28",
        f=LOGIC,
        loc="cutPayload — the cut drains the WALs before exporting",
        old="  pure def cutPayload(p: NodeState): List[WriteId] = p.data",
        new="  pure def cutPayload(p: NodeState): List[WriteId] = p.data.slice(0, max2(0, p.data.length() - 1))",
        exp="happyFullSyncTest + inv_payload_covers_grant + inv_applied_covered_by_data",
    ),
    dict(
        id="F29",
        f=LOGIC,
        loc="cutBelowGrant — the acked-write-loss detector's direction",
        old="    payload.length() < grant",
        new="    payload.length() > grant",
        exp="writeDuringTransferSurvivesTest (not(defects.cutBelowGrant) on an overship)",
    ),
    dict(
        id="F30",
        f=LOGIC,
        loc="cutAboveGrant — an exact cut is not an overship",
        old="    payload.length() > grant",
        new="    payload.length() >= grant",
        exp="happyFullSyncTest (not(coverage.overshipped))",
    ),
    # ---------------- logic: trailer install (TR-005/015/020) ----------------
    dict(
        id="F31",
        f=LOGIC,
        loc="applyInstallPayload — the payload becomes the dataset",
        old="    data: s.payload,",
        new="    data: r.data,",
        exp="happyFullSyncTest + inv_applied_covered_by_data",
    ),
    dict(
        id="F32",
        f=LOGIC,
        loc="applyInstallPayload — the trailer identity is adopted",
        old="    replid: s.granted_gen,",
        new="    replid: r.replid,",
        exp="happyFullSyncTest + inv_replid_offset_paired (tornIdentity)",
    ),
    dict(
        id="F33",
        f=LOGIC,
        loc="applyInstallPayload — a full resync clears the failover window id",
        old="    replid2: None,\n    second_offset: NO_WINDOW,",
        new="    replid2: r.replid2,\n    second_offset: NO_WINDOW,",
        exp="inv_replid_offset_paired (tornIdentity) + inv_failover_window_whole",
    ),
    dict(
        id="F34",
        f=LOGIC,
        loc="applyInstallPayload — a full resync clears the frozen boundary",
        old="    replid2: None,\n    second_offset: NO_WINDOW,",
        new="    replid2: None,\n    second_offset: r.second_offset,",
        exp="inv_replid_offset_paired (tornIdentity) + inv_failover_window_whole",
    ),
    dict(
        id="F35",
        f=LOGIC,
        loc="applyInstallPayload — the absolute pair installs the live head",
        old="    recv: s.grant_offset,\n    applied: s.grant_offset,",
        new="    recv: r.recv,\n    applied: s.grant_offset,",
        exp="inv_offsets_ordered + inv_replid_offset_paired (tornIdentity)",
    ),
    dict(
        id="F36",
        f=LOGIC,
        loc="applyInstallPayload — the absolute pair installs the applied offset",
        old="    recv: s.grant_offset,\n    applied: s.grant_offset,",
        new="    recv: s.grant_offset,\n    applied: r.applied,",
        exp="happyFullSyncTest (applied == 2)",
    ),
    dict(
        id="F37",
        f=LOGIC,
        loc="applyInstallPayload — the offsets come from the grant, not the payload end (disclosed reading)",
        old="    recv: s.grant_offset,\n    applied: s.grant_offset,",
        new="    recv: s.payload.length(),\n    applied: s.payload.length(),",
        exp="writeDuringTransferSurvivesTest (applied == 1 with a 2-write payload)",
    ),
    dict(
        id="F38",
        f=LOGIC,
        loc="installPairedOk — detector conjunct (window cleared)",
        old="      post.replid2 == None,\n      post.second_offset == NO_WINDOW,",
        new="      post.second_offset == NO_WINDOW,",
        exp="(pre-registered miss) detector self-mutation (A48/A49 class)",
    ),
    # ---------------- logic: splice availability (FM-012) ----------------
    dict(
        id="F39",
        f=LOGIC,
        loc="spliceRangeAvailable d1 — an empty replay range needs no history",
        old="    from >= p.recv or floorAdmits(p, from)",
        new="    floorAdmits(p, from)",
        exp="(pre-registered miss) no test splices at from == recv over an unarmed floor",
    ),
    dict(
        id="F40",
        f=LOGIC,
        loc="spliceRangeAvailable d2 — the window is re-checked at extraction",
        old="    from >= p.recv or floorAdmits(p, from)",
        new="    from >= p.recv",
        exp="writeDuringTransferSurvivesTest (splice at from < recv)",
    ),
    # ---------------- logic: frame classification / application (TR-014, FM-015) ----------------
    dict(
        id="F41",
        f=LOGIC,
        loc="classifyApply b1 — Appended is exactly the next position",
        old="    if (k == d.length() + 1) Appended\n    else if (k > d.length() + 1) Gapped",
        new="    if (k <= d.length() + 1) Appended\n    else if (k > d.length() + 1) Gapped",
        exp="writeDuringTransferSurvivesTest (coverage.reapplied)",
    ),
    dict(
        id="F42",
        f=LOGIC,
        loc="classifyApply b2 — a landing past the end is a gap",
        old="    else if (k > d.length() + 1) Gapped",
        new="    else if (k > d.length() + 1) Appended",
        exp="(pre-registered miss) Gapped unreachable under inv_applied_covered_by_data",
    ),
    dict(
        id="F43",
        f=LOGIC,
        loc="classifyApply b3 — same content at a held position is a re-apply",
        old="    else if (d.nth(k - 1) == w) Reapplied",
        new="    else if (d.nth(k - 1) != w) Reapplied",
        exp="writeDuringTransferSurvivesTest + overshippedTailMeetsFailoverTest",
    ),
    dict(
        id="F44",
        f=LOGIC,
        loc="classifyApply b4 — different content at a held position diverges",
        old="    else Diverged",
        new="    else Reapplied",
        exp="overshippedTailMeetsFailoverTest (coverage.forkedTailReplaced)",
    ),
    dict(
        id="F45",
        f=LOGIC,
        loc="applyFrameToData — a landing at a held position overwrites (fidelity fix)",
        old="    if (k == d.length() + 1) d.append(w) else d.replaceAt(k - 1, w)",
        new="    if (k == d.length() + 1) d.append(w) else d",
        exp="overshippedTailMeetsFailoverTest (final prefixAgrees)",
    ),
    dict(
        id="F46",
        f=LOGIC,
        loc="applyFrameToData — a landing at the next position appends",
        old="    if (k == d.length() + 1) d.append(w) else d.replaceAt(k - 1, w)",
        new="    if (k == d.length() + 1) d else d.replaceAt(k - 1, w)",
        exp="inv_applied_covered_by_data",
    ),
    # ---------------- logic: ACK ingest (TR-018, issue-21) ----------------
    dict(
        id="F47",
        f=LOGIC,
        loc="ackIsAboveHead — strictly above the head, not at it",
        old="  pure def ackIsAboveHead(p: NodeState, wire: Offset): bool = wire > p.recv",
        new="  pure def ackIsAboveHead(p: NodeState, wire: Offset): bool = wire >= p.recv",
        exp="ackAboveLiveHeadIgnoredTest (recordAckAt(1,2) at head 2)",
    ),
    dict(
        id="F48",
        f=LOGIC,
        loc="ackIsAboveHead — the validation exists at all",
        old="  pure def ackIsAboveHead(p: NodeState, wire: Offset): bool = wire > p.recv",
        new="  pure def ackIsAboveHead(p: NodeState, wire: Offset): bool = false",
        exp="ackAboveLiveHeadIgnoredTest + inv_ack_never_above_live_head",
    ),
    dict(
        id="F49",
        f=LOGIC,
        loc="applyAck — AckedOffset never regresses",
        old="    { ...s, acked: max2(s.acked, wire) }",
        new="    { ...s, acked: wire }",
        exp="(pre-registered miss) nothing pins ack monotonicity",
    ),
    # ---------------- logic: promotion (TR-016, FM-019/020) ----------------
    dict(
        id="F50",
        f=LOGIC,
        loc="applyPromote — the promoted node becomes a primary",
        old="    role: Primary,\n    replid: freshGen,",
        new="    role: n.role,\n    replid: freshGen,",
        exp="promotionMidSyncTest (role == Primary)",
    ),
    dict(
        id="F51",
        f=LOGIC,
        loc="applyPromote — promotion mints a fresh id",
        old="    role: Primary,\n    replid: freshGen,",
        new="    role: Primary,\n    replid: n.replid,",
        exp="promotionMidSyncTest + inv_replid_offset_paired (promotePairedOk)",
    ),
    dict(
        id="F52",
        f=LOGIC,
        loc="applyPromote — the outgoing id shifts into the window",
        old="    replid2: Some(n.replid),",
        new="    replid2: n.replid2,",
        exp="promotionMidSyncTest + inv_replid_offset_paired",
    ),
    dict(
        id="F53",
        f=LOGIC,
        loc="applyPromote — the window freezes at the applied offset, not the received head",
        old="    second_offset: n.applied,\n    recv: n.applied,",
        new="    second_offset: n.recv,\n    recv: n.applied,",
        exp="promotionMidSyncTest + inv_second_offset_not_above_live",
    ),
    dict(
        id="F54",
        f=LOGIC,
        loc="applyPromote — settle_at_applied discards the unapplied tail",
        old="    second_offset: n.applied,\n    recv: n.applied,",
        new="    second_offset: n.applied,\n    recv: n.recv,",
        exp="promotionMidSyncTest (recv == 2)",
    ),
    dict(
        id="F55",
        f=LOGIC,
        loc="applyPromote — the backlog floor re-arms at the same boundary",
        old="    floor: n.applied,\n    link: None,",
        new="    floor: UNARMED,\n    link: None,",
        exp="promotionMidSyncTest (floor == 2)",
    ),
    dict(
        id="F56",
        f=LOGIC,
        loc="applyPromote — the promoted node drops its own link",
        old="    floor: n.applied,\n    link: None,",
        new="    floor: n.applied,\n    link: n.link,",
        exp="inv_link_points_at_a_live_session",
    ),
    dict(
        id="F57",
        f=LOGIC,
        loc="promotePairedOk — detector conjunct (settle)",
        old="      post.recv == pre.applied,\n      post.applied == pre.applied,",
        new="      post.applied == pre.applied,",
        exp="(pre-registered miss) detector self-mutation",
    ),
    # ---------------- logic: restart (TR-021, issue-24) ----------------
    dict(
        id="F58",
        f=LOGIC,
        loc="restartKeepsIdentity c2 — identity survives only an intact recovery",
        old="    not(unclean) and keep == pre.applied",
        new="    not(unclean)",
        exp="inv_identity_pair_monotone (a clean restart that lost data keeps its id)",
    ),
    dict(
        id="F59",
        f=LOGIC,
        loc="restartKeepsIdentity c1 — an unclean restart always reminds",
        old="    not(unclean) and keep == pre.applied",
        new="    keep == pre.applied",
        exp="(pre-registered miss) no test restarts unclean at a full recovery point",
    ),
    dict(
        id="F60",
        f=LOGIC,
        loc="applyRestart (keep branch) — the dataset is truncated to what was recovered",
        old="      { ...pre, role: Primary, data: pre.data.slice(0, keep), recv: keep, applied: keep,\n        floor: UNARMED, link: None, last_departure: None }",
        new="      { ...pre, role: Primary, data: pre.data, recv: keep, applied: keep,\n        floor: UNARMED, link: None, last_departure: None }",
        exp="inv_restart_pairs_offset (restartOffsetTorn)",
    ),
    dict(
        id="F61",
        f=LOGIC,
        loc="applyRestart (remint branch) — the dataset is truncated to what was recovered",
        old="      { ...pre, role: Primary, data: pre.data.slice(0, keep), recv: keep, applied: keep,\n        floor: UNARMED, link: None, last_departure: None,\n        replid: freshGen,",
        new="      { ...pre, role: Primary, data: pre.data, recv: keep, applied: keep,\n        floor: UNARMED, link: None, last_departure: None,\n        replid: freshGen,",
        exp="uncleanRestartMintsFreshIdTest + inv_restart_pairs_offset",
    ),
    dict(
        id="F62",
        f=LOGIC,
        loc="applyRestart (remint branch) — the live head commits with the data",
        old="        floor: UNARMED, link: None, last_departure: None,\n        replid: freshGen, replid2: Some(pre.replid), second_offset: keep }",
        new="        floor: UNARMED, link: None, last_departure: None, recv: pre.recv,\n        replid: freshGen, replid2: Some(pre.replid), second_offset: keep }",
        exp="uncleanRestartMintsFreshIdTest + inv_restart_pairs_offset",
    ),
    dict(
        id="F63",
        f=LOGIC,
        loc="applyRestart (remint branch) — the applied offset commits with the data",
        old="        floor: UNARMED, link: None, last_departure: None,\n        replid: freshGen, replid2: Some(pre.replid), second_offset: keep }",
        new="        floor: UNARMED, link: None, last_departure: None, applied: pre.applied,\n        replid: freshGen, replid2: Some(pre.replid), second_offset: keep }",
        exp="inv_applied_covered_by_data + inv_restart_pairs_offset",
    ),
    dict(
        id="F64",
        f=LOGIC,
        loc="applyRestart (remint branch) — a reboot starts with an unarmed backlog",
        old="        floor: UNARMED, link: None, last_departure: None,\n        replid: freshGen, replid2: Some(pre.replid), second_offset: keep }",
        new="        floor: keep, link: None, last_departure: None,\n        replid: freshGen, replid2: Some(pre.replid), second_offset: keep }",
        exp="(pre-registered miss) the model's backlog is a floor abstraction; data is never discarded",
    ),
    dict(
        id="F65",
        f=LOGIC,
        loc="applyRestart (remint branch) — a reboot drops its link",
        old="        floor: UNARMED, link: None, last_departure: None,\n        replid: freshGen, replid2: Some(pre.replid), second_offset: keep }",
        new="        floor: UNARMED, link: pre.link, last_departure: None,\n        replid: freshGen, replid2: Some(pre.replid), second_offset: keep }",
        exp="(pre-registered miss) equivalent: unlinkedFrom clears it at the call site",
    ),
    dict(
        id="F66",
        f=LOGIC,
        loc="applyRestart (remint branch) — a reboot forgets the last departure",
        old="        floor: UNARMED, link: None, last_departure: None,\n        replid: freshGen, replid2: Some(pre.replid), second_offset: keep }",
        new="        floor: UNARMED, link: None, last_departure: pre.last_departure,\n        replid: freshGen, replid2: Some(pre.replid), second_offset: keep }",
        exp="(pre-registered miss) last_departure is the feed-gate model's subject",
    ),
    dict(
        id="F67",
        f=LOGIC,
        loc="applyRestart (remint branch) — a lossy reboot mints a fresh id",
        old="        replid: freshGen, replid2: Some(pre.replid), second_offset: keep }",
        new="        replid: pre.replid, replid2: Some(pre.replid), second_offset: keep }",
        exp="uncleanRestartMintsFreshIdTest + inv_identity_pair_monotone",
    ),
    dict(
        id="F68",
        f=LOGIC,
        loc="applyRestart (remint branch) — the outgoing id shifts into the window",
        old="        replid: freshGen, replid2: Some(pre.replid), second_offset: keep }",
        new="        replid: freshGen, replid2: pre.replid2, second_offset: keep }",
        exp="uncleanRestartMintsFreshIdTest + inv_replid_offset_paired",
    ),
    dict(
        id="F69",
        f=LOGIC,
        loc="applyRestart (remint branch) — the window freezes at the proven offset",
        old="        replid: freshGen, replid2: Some(pre.replid), second_offset: keep }",
        new="        replid: freshGen, replid2: Some(pre.replid), second_offset: pre.applied }",
        exp="uncleanRestartMintsFreshIdTest + inv_second_offset_not_above_live",
    ),
    dict(
        id="F70",
        f=LOGIC,
        loc="restartOffsetPairedOk — detector conjunct (applied)",
        old="    post.recv == post.data.length() and post.applied == post.data.length()",
        new="    post.recv == post.data.length()",
        exp="(pre-registered miss) detector self-mutation",
    ),
    dict(
        id="F71",
        f=LOGIC,
        loc="identityPairOk — the lexicographic disjunct is load-bearing",
        old="    (curGen == prevGen and curOff == prevOff) or lexGt((curGen, curOff), (prevGen, prevOff))",
        new="    (curGen == prevGen and curOff == prevOff)",
        exp="inv_identity_pair_monotone violated by the unmutated model (clause is tight)",
    ),
    dict(
        id="F72",
        f=LOGIC,
        loc="identityPairOk — the offset half of the order is load-bearing",
        old="    (curGen == prevGen and curOff == prevOff) or lexGt((curGen, curOff), (prevGen, prevOff))",
        new="    (curGen == prevGen and curOff == prevOff) or curGen > prevGen",
        exp="(pre-registered miss) weaker oracle; falsified only by F58's shape",
    ),
    dict(
        id="F73",
        f=LOGIC,
        loc="prefixAgrees — content agreement, not just length",
        old="    else 0.to(n - 1).forall(i => d.nth(i) == hist.nth(i))",
        new="    else true",
        exp="(pre-registered miss) weaker oracle; falsified only by a divergence row",
    ),
]

ROWS += [
    # ---------------- machine: helpers / init ----------------
    dict(
        id="M01",
        f=MACH,
        loc="linkIs — the link must name *this* session, not merely exist",
        old="  pure def linkIs(r: NodeState, sid: SessionId): bool =\n    optExists(r.link, k => k == sid)",
        new="  pure def linkIs(r: NodeState, sid: SessionId): bool =\n    r.link != None",
        exp="inv_no_acked_write_lost_across_fullsync (a corpse session installs)",
    ),
    dict(
        id="M02",
        f=MACH,
        loc="pairSnapshot — the shadow tracks the live head",
        old="      off: nodes.get(n).recv,",
        new="      off: nodes.get(n).applied,",
        exp="(pre-registered miss) equivalent while a primary's head is settled",
    ),
    dict(
        id="M03",
        f=MACH,
        loc="pairSnapshot — the shadow records the role",
        old="      primary: nodes.get(n).role == Primary,",
        new="      primary: true,",
        exp="inv_identity_pair_monotone (a promotion's predecessor was no primary)",
    ),
    dict(
        id="M04",
        f=MACH,
        loc="ctlNextD — the shadow refreshes every step",
        old="    prev_pair: pairSnapshot,",
        new="    prev_pair: ctl.prev_pair,",
        exp="(pre-registered miss) destroys the oracle rather than the model",
    ),
    dict(
        id="M05",
        f=MACH,
        loc="freeSids — a free slot is a disconnected one",
        old="    SIDS.filter(k => sessions.get(k).phase == Disconnected)",
        new="    SIDS.filter(k => sessions.get(k).phase != Disconnected)",
        exp="(pre-registered N/A) steering-only; psyncRequestAs re-checks the slot",
    ),
    dict(
        id="M06",
        f=MACH,
        loc="sessionsWithout — a restart clears the slots it was the replica of",
        old="      if (s.primary == n or s.replica == n) { ...s, phase: Disconnected } else s",
        new="      if (s.primary == n) { ...s, phase: Disconnected } else s",
        exp="inv_link_points_at_a_live_session / inv_one_session_per_announced_identity",
    ),
    dict(
        id="M07",
        f=MACH,
        loc="unlinkedFrom — a restart kills every link into its sessions",
        old="      if (dead) { ...nm, link: None } else nm",
        new="      nm",
        exp="inv_link_points_at_a_live_session",
    ),
    dict(
        id="M08",
        f=MACH,
        loc="init — the initial primary heads a real generation",
        old="        { role: Primary, data: List(), replid: FIRST_GEN, replid2: None,",
        new="        { role: Primary, data: List(), replid: NO_HISTORY, replid2: None,",
        exp="happyFullSyncTest (grant arm) / inv_partial_grant_sound",
    ),
    dict(
        id="M09",
        f=MACH,
        loc="init — non-primaries start with no history",
        old="        { role: Replica, data: List(), replid: NO_HISTORY, replid2: None,",
        new="        { role: Replica, data: List(), replid: FIRST_GEN, replid2: None,",
        exp="happyFullSyncTest (a virgin replica gets a PartialGrant)",
    ),
    dict(
        id="M10",
        f=MACH,
        loc="init — nothing starts with an armed backlog floor",
        old="          second_offset: NO_WINDOW, recv: 0, applied: 0, floor: UNARMED,\n          link: None, last_departure: None, acks_ignored: 0 }\n      else",
        new="          second_offset: NO_WINDOW, recv: 0, applied: 0, floor: 0,\n          link: None, last_departure: None, acks_ignored: 0 }\n      else",
        exp="(pre-registered miss) an armed floor at 0 admits everything",
    ),
    dict(
        id="M11",
        f=MACH,
        loc="init — the generation counter starts past the initial id",
        old="        next_gen: FIRST_GEN + 1,",
        new="        next_gen: FIRST_GEN,",
        exp="inv_replids_distinct (a promotion mints the id it already holds)",
    ),
    dict(
        id="M12",
        f=MACH,
        loc="init — the pairing shadow starts from the initial state",
        old="          gen: n0.get(n).replid, off: n0.get(n).recv,",
        new="          gen: n0.get(n).replid, off: 0,",
        exp="(pre-registered N/A) every initial recv is already 0",
    ),
    # ---------------- machine: write / evict wiring ----------------
    dict(
        id="M13",
        f=MACH,
        loc="writeOnPrimaryAs g1 — only a primary accepts writes",
        old="    nodes.get(p).role == Primary,\n    ctl.next_write <= MAX_WRITES,",
        new="    ctl.next_write <= MAX_WRITES,",
        exp="inv_no_acked_write_lost_across_fullsync (a replica forks its own history)",
    ),
    dict(
        id="M14",
        f=MACH,
        loc="writeOnPrimaryAs — the write id is consumed",
        old="    ctl' = ctlNext(1, 0),",
        new="    ctl' = ctlNext(0, 0),",
        exp="(pre-registered miss) duplicate ids only make histories agree more",
    ),
    dict(
        id="M15",
        f=MACH,
        loc="evictBacklogAs — eviction actually raises the floor",
        old="    nodes' = nodes.set(p, applyEvictBacklog(nodes.get(p))),\n    keepSessions,\n    keepCtl,",
        new="    keepNodes,\n    keepSessions,\n    keepCtl,",
        exp="backlogEvictionForcesFullResyncTest (floor == 2)",
    ),
    # ---------------- machine: PSYNC guards ----------------
    dict(
        id="M16",
        f=MACH,
        loc="psyncRequestAs g1 — a node never replicates from itself",
        old="      r != p,\n      rn.role == Replica,",
        new="      rn.role == Replica,",
        exp="(pre-registered miss) role guards already exclude r == p",
    ),
    dict(
        id="M17",
        f=MACH,
        loc="psyncRequestAs g2 — only a replica issues PSYNC",
        old="      rn.role == Replica,\n      pn.role == Primary,",
        new="      pn.role == Primary,",
        exp="inv_identity_pair_monotone (a primary rewinds under PSYNC)",
    ),
    dict(
        id="M18",
        f=MACH,
        loc="psyncRequestAs g3 — PSYNC targets a primary",
        old="      pn.role == Primary,\n      rn.link == None,",
        new="      rn.link == None,",
        exp="inv_no_acked_write_lost_across_fullsync (chained replica history)",
    ),
    dict(
        id="M19",
        f=MACH,
        loc="psyncRequestAs g4 — an already-linked replica does not re-PSYNC",
        old="      rn.link == None,\n      sessions.get(sid).phase == Disconnected,",
        new="      sessions.get(sid).phase == Disconnected,",
        exp="inv_link_points_at_a_live_session / inv_one_session_per_announced_identity",
    ),
    dict(
        id="M20",
        f=MACH,
        loc="psyncRequestAs g5 — the target slot must be free",
        old="      sessions.get(sid).phase == Disconnected,\n      nodes' = nodesPost,",
        new="      nodes' = nodesPost,",
        exp="inv_link_points_at_a_live_session (a live session is overwritten)",
    ),
    # ---------------- machine: PSYNC effects ----------------
    dict(
        id="M21",
        f=MACH,
        loc="psyncRequestAs — an announced peer registers its identity",
        old="      identity: if (announced) Some(r) else None,",
        new="      identity: None,",
        exp="supersededPredecessorTest (coverage.superseded)",
    ),
    dict(
        id="M22",
        f=MACH,
        loc="psyncRequestAs — an unannounced peer is dedup-exempt",
        old="      identity: if (announced) Some(r) else None,",
        new="      identity: Some(r),",
        exp="(pre-registered miss) dedup only ever removes sessions",
    ),
    dict(
        id="M23",
        f=MACH,
        loc="psyncRequestAs — a partial grant skips the checkpoint",
        old="      phase: if (arm == PartialGrant) Connecting else PreparingCheckpoint,",
        new="      phase: PreparingCheckpoint,",
        exp="partialResyncViaReplid2WindowTest (phase == Connecting)",
    ),
    dict(
        id="M24",
        f=MACH,
        loc="psyncRequestAs — a full snapshot starts at checkpoint preparation",
        old="      phase: if (arm == PartialGrant) Connecting else PreparingCheckpoint,",
        new="      phase: Connecting,",
        exp="happyFullSyncTest (cutCheckpointAt is disabled)",
    ),
    dict(
        id="M25",
        f=MACH,
        loc="psyncRequestAs — the grant carries the primary's generation",
        old="      granted_gen: pn.replid,",
        new="      granted_gen: rn.replid,",
        exp="happyFullSyncTest + inv_replid_offset_paired (tornIdentity)",
    ),
    dict(
        id="M26",
        f=MACH,
        loc="psyncRequestAs — the full arm captures the offset before the cut (FM-004)",
        old="      grant_offset: if (arm == PartialGrant) rn.applied else pn.recv,",
        new="      grant_offset: if (arm == PartialGrant) rn.applied else pn.recv + 1,",
        exp="inv_applied_covered_by_data + inv_payload_covers_grant",
    ),
    dict(
        id="M27",
        f=MACH,
        loc="psyncRequestAs — the partial arm resumes at what the replica applied",
        old="      grant_offset: if (arm == PartialGrant) rn.applied else pn.recv,",
        new="      grant_offset: if (arm == PartialGrant) rn.recv else pn.recv,",
        exp="partialResyncViaReplid2WindowTest (grant_offset == 1)",
    ),
    dict(
        id="M28",
        f=MACH,
        loc="psyncRequestAs — a fresh session starts with no ack credited",
        old="      acked: 0,\n      resume_offset: 0,\n    }\n    val rPost = {",
        new="      acked: pn.recv,\n      resume_offset: 0,\n    }\n    val rPost = {",
        exp="(pre-registered miss) nothing relates AckedOffset to replica progress",
    ),
    dict(
        id="M29",
        f=MACH,
        loc="psyncRequestAs — the replica links to the granted session",
        old="      link: Some(sid),",
        new="      link: rn.link,",
        exp="happyFullSyncTest (deliverPayloadAt's linkIs guard disables)",
    ),
    dict(
        id="M30",
        f=MACH,
        loc="psyncRequestAs — a +CONTINUE shifts the granted id in (TR-019)",
        old="      replid: if (arm == PartialGrant) pn.replid else rn.replid,",
        new="      replid: rn.replid,",
        exp="partialResyncViaReplid2WindowTest (replid == 2)",
    ),
    dict(
        id="M31",
        f=MACH,
        loc="psyncRequestAs — the full arm adopts no id before the trailer",
        old="      replid: if (arm == PartialGrant) pn.replid else rn.replid,",
        new="      replid: pn.replid,",
        exp="inv_no_acked_write_lost_across_fullsync (id adopted before the data)",
    ),
    dict(
        id="M32",
        f=MACH,
        loc="psyncRequestAs — the reconnect rewinds recv to what was applied",
        old="      recv: if (arm == PartialGrant) rn.applied else 0,",
        new="      recv: if (arm == PartialGrant) rn.recv else 0,",
        exp="(pre-registered miss) the discarded-tail leg; needs a run test",
    ),
    dict(
        id="M33",
        f=MACH,
        loc="psyncRequestAs — the full arm rewinds to zero",
        old="      recv: if (arm == PartialGrant) rn.applied else 0,",
        new="      recv: if (arm == PartialGrant) rn.applied else rn.recv,",
        exp="inv_offsets_ordered (recv above a zeroed applied after install)",
    ),
    dict(
        id="M34",
        f=MACH,
        loc="psyncRequestAs — the applied offset rewinds with recv",
        old="      applied: if (arm == PartialGrant) rn.applied else 0,",
        new="      applied: if (arm == PartialGrant) rn.applied else rn.applied,",
        exp="happyFullSyncTest / inv_applied_covered_by_data",
    ),
    # ---------------- machine: dedup / victims (issue-22) ----------------
    dict(
        id="M35",
        f=MACH,
        loc="victims c1 — only an announced registration dedups",
        old="      announced,\n      k != sid,",
        new="      k != sid,",
        exp="(pre-registered miss) unannounced dedup only removes more sessions",
    ),
    dict(
        id="M36",
        f=MACH,
        loc="victims c2 — a registration never kicks itself",
        old="      k != sid,\n      sessions.get(k).phase != Disconnected,",
        new="      sessions.get(k).phase != Disconnected,",
        exp="happyFullSyncTest (the granted slot is immediately disconnected)",
    ),
    dict(
        id="M37",
        f=MACH,
        loc="victims c4 — dedup is per-primary",
        old="      sessions.get(k).primary == p,\n      sessions.get(k).identity == Some(r),",
        new="      sessions.get(k).identity == Some(r),",
        exp="(pre-registered miss) cross-primary kick needs a run test",
    ),
    dict(
        id="M38",
        f=MACH,
        loc="victims c5 — dedup is keyed on the node identity",
        old="      sessions.get(k).identity == Some(r),",
        new="      sessions.get(k).identity != None,",
        exp="(pre-registered miss) over-kicking; needs a run test",
    ),
    dict(
        id="M39",
        f=MACH,
        loc="psyncRequestAs — the victims are actually disconnected",
        old="        else if (victims.contains(k)) { ...sessions.get(k), phase: Disconnected }",
        new="        else if (false) { ...sessions.get(k), phase: Disconnected }",
        exp="supersededPredecessorTest + inv_one_session_per_announced_identity",
    ),
    dict(
        id="M40",
        f=MACH,
        loc="psyncRequestAs — the superseded-departure ghost reads the post-state",
        old="          victims.size() > 0 and nodesPost.get(p).last_departure != pn.last_departure),",
        new="          false),",
        exp="(pre-registered miss) ghost self-mutation; the model never sets it",
    ),
    dict(
        id="M41",
        f=MACH,
        loc="psyncRequestAs — the grant-below-floor ghost is armed",
        old="          arm == PartialGrant and not(floorAdmits(pn, rn.applied))),",
        new="          false),",
        exp="(pre-registered miss) ghost self-mutation (F12 is the behaviour row)",
    ),
    dict(
        id="M42",
        f=MACH,
        loc="psyncRequestAs — the foreign-history ghost is armed",
        old="          arm == PartialGrant and not(windowContains(pn, rn.replid, rn.applied))),",
        new="          false),",
        exp="(pre-registered miss) ghost self-mutation (F11 is the behaviour row)",
    ),
    dict(
        id="M43",
        f=MACH,
        loc="psyncRequestAs — the secondary-window coverage latch",
        old="          arm == PartialGrant and grantedViaSecondary(pn, rn)),",
        new="          false),",
        exp="partialResyncViaReplid2WindowTest (coverage.partialViaSecondary)",
    ),
    dict(
        id="M44",
        f=MACH,
        loc="psyncRequestAs — the eviction-degradation coverage latch",
        old="          arm == FullSnapshot and degradedByFloor(pn, rn)),",
        new="          false),",
        exp="backlogEvictionForcesFullResyncTest (coverage.evictionForcedFull)",
    ),
    dict(
        id="M45",
        f=MACH,
        loc="psyncRequestAs — the superseded coverage latch",
        old="        superseded: latch(coverage.superseded, victims.size() > 0),",
        new="        superseded: latch(coverage.superseded, false),",
        exp="supersededPredecessorTest (coverage.superseded)",
    ),
    # ---------------- machine: cut ----------------
    dict(
        id="M46",
        f=MACH,
        loc="cutCheckpointAt g1 — a cut happens once, at the preparing phase",
        old="      s.phase == PreparingCheckpoint,\n      keepNodes,",
        new="      s.phase != Disconnected,\n      keepNodes,",
        exp="inv_no_acked_write_lost_across_fullsync / inv_applied_covered_by_data",
    ),
    dict(
        id="M47",
        f=MACH,
        loc="cutCheckpointAt — the cut advances the session",
        old="        { ...s, phase: StreamingCheckpoint, payload: payload, payload_cut: true }),",
        new="        { ...s, phase: PreparingCheckpoint, payload: payload, payload_cut: true }),",
        exp="happyFullSyncTest (deliverPayloadAt disabled)",
    ),
    dict(
        id="M48",
        f=MACH,
        loc="cutCheckpointAt — the exported payload is the cut",
        old="        { ...s, phase: StreamingCheckpoint, payload: payload, payload_cut: true }),",
        new="        { ...s, phase: StreamingCheckpoint, payload: s.payload, payload_cut: true }),",
        exp="happyFullSyncTest + inv_applied_covered_by_data",
    ),
    dict(
        id="M49",
        f=MACH,
        loc="cutCheckpointAt — payload_cut records that a cut happened",
        old="        { ...s, phase: StreamingCheckpoint, payload: payload, payload_cut: true }),",
        new="        { ...s, phase: StreamingCheckpoint, payload: payload, payload_cut: false }),",
        exp="(pre-registered miss) payload_cut is read nowhere — dead field",
    ),
    dict(
        id="M50",
        f=MACH,
        loc="cutCheckpointAt — the acked-loss ghost is armed",
        old="        cutBelowGrant: latch(defects.cutBelowGrant, cutBelowGrant(payload, s.grant_offset)) },",
        new="        cutBelowGrant: latch(defects.cutBelowGrant, false) },",
        exp="(pre-registered miss) ghost self-mutation (F28 is the behaviour row)",
    ),
    dict(
        id="M51",
        f=MACH,
        loc="cutCheckpointAt — the overship coverage latch",
        old="        overshipped: latch(coverage.overshipped, cutAboveGrant(payload, s.grant_offset)) },",
        new="        overshipped: latch(coverage.overshipped, false) },",
        exp="writeDuringTransferSurvivesTest (coverage.overshipped)",
    ),
    # ---------------- machine: deliver (corpse guard) ----------------
    dict(
        id="M52",
        f=MACH,
        loc="deliverPayloadAt g1 — the trailer lands once, after the cut",
        old="      s.phase == StreamingCheckpoint,\n      // Only the replica's own live link may write its dataset. A corpse session",
        new="      s.phase != Disconnected,\n      // Only the replica's own live link may write its dataset. A corpse session",
        exp="inv_applied_covered_by_data (an uncut empty payload installs a grant)",
    ),
    dict(
        id="M53",
        f=MACH,
        loc="deliverPayloadAt g2 — the corpse-session guard is load-bearing",
        old="      linkIs(rn, sid),\n      nodes' = nodes.set(s.replica, rPost),",
        new="      nodes' = nodes.set(s.replica, rPost),",
        exp="inv_no_acked_write_lost_across_fullsync (a corpse overwrites a live dataset)",
    ),
    dict(
        id="M54",
        f=MACH,
        loc="deliverPayloadAt — the install commits to the replica",
        old="      nodes' = nodes.set(s.replica, rPost),\n      sessions' = sessions.set(sid, { ...s, phase: PayloadInstalled }),",
        new="      keepNodes,\n      sessions' = sessions.set(sid, { ...s, phase: PayloadInstalled }),",
        exp="happyFullSyncTest (data == payload)",
    ),
    dict(
        id="M55",
        f=MACH,
        loc="deliverPayloadAt — the session advances to PayloadInstalled",
        old="      sessions' = sessions.set(sid, { ...s, phase: PayloadInstalled }),",
        new="      sessions' = sessions.set(sid, { ...s, phase: Streaming }),",
        exp="happyFullSyncTest (phase == PayloadInstalled) / inv_splice_continuity",
    ),
    dict(
        id="M56",
        f=MACH,
        loc="deliverPayloadAt — the torn-identity ghost is armed",
        old="        tornIdentity: latch(defects.tornIdentity, not(installPairedOk(rPost, s))) },",
        new="        tornIdentity: latch(defects.tornIdentity, false) },",
        exp="(pre-registered miss) ghost self-mutation (F32-F36 are the behaviour rows)",
    ),
    # ---------------- machine: splice ----------------
    dict(
        id="M57",
        f=MACH,
        loc="spliceStreamAt g1 — streaming starts from an installed or partial session",
        old="      s.phase == PayloadInstalled or s.phase == Connecting,\n      spliceRangeAvailable(pn, s.grant_offset),",
        new="      s.phase != Disconnected,\n      spliceRangeAvailable(pn, s.grant_offset),",
        exp="inv_no_acked_write_lost_across_fullsync (streaming before the trailer)",
    ),
    dict(
        id="M58",
        f=MACH,
        loc="spliceStreamAt g2 — the replay range is re-checked at extraction",
        old="      spliceRangeAvailable(pn, s.grant_offset),\n      keepNodes,",
        new="      keepNodes,",
        exp="spliceOverEvictedRangeFailsTest (.fail() test now succeeds)",
    ),
    dict(
        id="M59",
        f=MACH,
        loc="spliceStreamAt — the resume point is seeded from the grant",
        old="        { ...s, phase: Streaming, resume_offset: s.grant_offset }),",
        new="        { ...s, phase: Streaming, resume_offset: 0 }),",
        exp="(pre-registered miss) TR-002 resume seed is unasserted",
    ),
    dict(
        id="M60",
        f=MACH,
        loc="spliceStreamAt — the session reaches Streaming",
        old="        { ...s, phase: Streaming, resume_offset: s.grant_offset }),",
        new="        { ...s, phase: PayloadInstalled, resume_offset: s.grant_offset }),",
        exp="happyFullSyncTest (phase == Streaming)",
    ),
    dict(
        id="M61",
        f=MACH,
        loc="spliceStreamAt — the full-sync streaming coverage latch",
        old="        fullSyncStreaming: latch(coverage.fullSyncStreaming, s.arm == FullSnapshot) },",
        new="        fullSyncStreaming: latch(coverage.fullSyncStreaming, true) },",
        exp="(pre-registered miss) over-latch with no negative assertion",
    ),
    # ---------------- machine: abandon ----------------
    dict(
        id="M62",
        f=MACH,
        loc="abandonSpliceAt g2 — abandonment needs an unavailable range",
        old="      not(spliceRangeAvailable(pn, s.grant_offset)),\n      nodes' = nodes.set(s.replica, { ...rn, link: None }),",
        new="      nodes' = nodes.set(s.replica, { ...rn, link: None }),",
        exp="happyFullSyncTest / truncatedSpliceIsAbandonedTest",
    ),
    dict(
        id="M63",
        f=MACH,
        loc="abandonSpliceAt — the replica's link dies with the attempt",
        old="      nodes' = nodes.set(s.replica, { ...rn, link: None }),\n      sessions' = sessions.set(sid, { ...s, phase: Disconnected }),",
        new="      keepNodes,\n      sessions' = sessions.set(sid, { ...s, phase: Disconnected }),",
        exp="inv_link_points_at_a_live_session",
    ),
    dict(
        id="M64",
        f=MACH,
        loc="abandonSpliceAt — the session is torn down, never streamed",
        old="      sessions' = sessions.set(sid, { ...s, phase: Disconnected }),\n      keepCtl,\n      keepDefects,\n      coverage' = { ...coverage,\n        spliceAbandoned: latch(coverage.spliceAbandoned, true) },",
        new="      sessions' = sessions.set(sid, { ...s, phase: Streaming }),\n      keepCtl,\n      keepDefects,\n      coverage' = { ...coverage,\n        spliceAbandoned: latch(coverage.spliceAbandoned, true) },",
        exp="truncatedSpliceIsAbandonedTest (phase == Disconnected)",
    ),
    dict(
        id="M65",
        f=MACH,
        loc="abandonSpliceAt — the abandonment coverage latch",
        old="        spliceAbandoned: latch(coverage.spliceAbandoned, true) },",
        new="        spliceAbandoned: latch(coverage.spliceAbandoned, false) },",
        exp="truncatedSpliceIsAbandonedTest (coverage.spliceAbandoned)",
    ),
    # ---------------- machine: receive ----------------
    dict(
        id="M66",
        f=MACH,
        loc="receiveFrameAt g1 — frames only arrive on a streaming session",
        old="      s.phase == Streaming,\n      linkIs(rn, sid),\n      rn.recv < pn.recv,",
        new="      s.phase != Disconnected,\n      linkIs(rn, sid),\n      rn.recv < pn.recv,",
        exp="inv_no_acked_write_lost_across_fullsync (frames before the trailer)",
    ),
    dict(
        id="M67",
        f=MACH,
        loc="receiveFrameAt g2 — the corpse-session guard is load-bearing",
        old="      linkIs(rn, sid),\n      rn.recv < pn.recv,",
        new="      rn.recv < pn.recv,",
        exp="inv_offsets_ordered / inv_no_acked_write_lost_across_fullsync",
    ),
    dict(
        id="M68",
        f=MACH,
        loc="receiveFrameAt g3 — a replica never receives past the primary's head",
        old="      rn.recv < pn.recv,\n      rn.recv < pn.data.length(),",
        new="      rn.recv < pn.data.length(),",
        exp="(pre-registered miss) recv above the primary head is unasserted",
    ),
    dict(
        id="M69",
        f=MACH,
        loc="receiveFrameAt g4 — a frame must exist to be received",
        old="      rn.recv < pn.data.length(),\n      nodes' = nodes.set(s.replica, { ...rn, recv: rn.recv + 1 }),",
        new="      nodes' = nodes.set(s.replica, { ...rn, recv: rn.recv + 1 }),",
        exp="inv_applied_covered_by_data (applyFrameAt's sentinel read)",
    ),
    dict(
        id="M70",
        f=MACH,
        loc="receiveFrameAt — reception advances the received offset",
        old="      nodes' = nodes.set(s.replica, { ...rn, recv: rn.recv + 1 }),\n      keepSessions,",
        new="      keepNodes,\n      keepSessions,",
        exp="happyFullSyncTest / writeDuringTransferSurvivesTest",
    ),
    # ---------------- machine: apply ----------------
    dict(
        id="M71",
        f=MACH,
        loc="applyFrameAt g1 — frames only land on a streaming session",
        old="      s.phase == Streaming,\n      linkIs(rn, sid),\n      rn.applied < rn.recv,",
        new="      s.phase != Disconnected,\n      linkIs(rn, sid),\n      rn.applied < rn.recv,",
        exp="inv_no_acked_write_lost_across_fullsync",
    ),
    dict(
        id="M72",
        f=MACH,
        loc="applyFrameAt g2 — the corpse-session guard is load-bearing",
        old="      linkIs(rn, sid),\n      rn.applied < rn.recv,",
        new="      rn.applied < rn.recv,",
        exp="inv_no_acked_write_lost_across_fullsync (a corpse lands foreign frames)",
    ),
    dict(
        id="M73",
        f=MACH,
        loc="applyFrameAt g3 — only received frames are applied",
        old="      rn.applied < rn.recv,\n      k <= pn.data.length(),",
        new="      k <= pn.data.length(),",
        exp="inv_offsets_ordered",
    ),
    dict(
        id="M74",
        f=MACH,
        loc="applyFrameAt g4 — the sentinel read is never committed",
        old="      k <= pn.data.length(),\n      nodes' = nodes.set(s.replica,",
        new="      nodes' = nodes.set(s.replica,",
        exp="inv_no_acked_write_lost_across_fullsync (NO_HISTORY sentinel lands)",
    ),
    dict(
        id="M75",
        f=MACH,
        loc="applyFrameAt — the frame is written into the dataset",
        old="        { ...rn, data: applyFrameToData(rn.data, k, w), applied: k }),",
        new="        { ...rn, data: rn.data, applied: k }),",
        exp="inv_applied_covered_by_data",
    ),
    dict(
        id="M76",
        f=MACH,
        loc="applyFrameAt — the applied offset advances with the frame",
        old="        { ...rn, data: applyFrameToData(rn.data, k, w), applied: k }),",
        new="        { ...rn, data: applyFrameToData(rn.data, k, w), applied: rn.applied }),",
        exp="happyFullSyncTest (applied == 2)",
    ),
    dict(
        id="M77",
        f=MACH,
        loc="applyFrameAt — the splice-gap ghost is armed",
        old="        spliceGap: latch(defects.spliceGap, outcome == Gapped),",
        new="        spliceGap: latch(defects.spliceGap, false),",
        exp="(pre-registered miss) ghost self-mutation; Gapped is unreachable",
    ),
    dict(
        id="M78",
        f=MACH,
        loc="applyFrameAt — the divergence ghost is armed",
        old="        spliceDiverged: latch(defects.spliceDiverged,\n          outcome == Diverged and k <= s.resume_offset) },",
        new="        spliceDiverged: latch(defects.spliceDiverged, false) },",
        exp="(pre-registered miss) ghost self-mutation (F44 is the behaviour row)",
    ),
    dict(
        id="M79",
        f=MACH,
        loc="applyFrameAt — divergence is a defect only inside the claimed window",
        old="          outcome == Diverged and k <= s.resume_offset) },",
        new="          outcome == Diverged) },",
        exp="inv_splice_continuity violated by the unmutated model (disclosed residue)",
    ),
    dict(
        id="M80",
        f=MACH,
        loc="applyFrameAt — the reapplied coverage latch",
        old="        reapplied: latch(coverage.reapplied, outcome == Reapplied),",
        new="        reapplied: latch(coverage.reapplied, false),",
        exp="writeDuringTransferSurvivesTest (coverage.reapplied)",
    ),
    dict(
        id="M81",
        f=MACH,
        loc="applyFrameAt — the forked-tail coverage latch",
        old="        forkedTailReplaced: latch(coverage.forkedTailReplaced,\n          outcome == Diverged and k > s.resume_offset),",
        new="        forkedTailReplaced: latch(coverage.forkedTailReplaced, false),",
        exp="overshippedTailMeetsFailoverTest (coverage.forkedTailReplaced)",
    ),
    dict(
        id="M82",
        f=MACH,
        loc="applyFrameAt — the tail-applied coverage latch",
        old="        tailApplied: latch(coverage.tailApplied, true) },",
        new="        tailApplied: latch(coverage.tailApplied, false) },",
        exp="(pre-registered miss) witness-only latch with no test assertion",
    ),
    # ---------------- machine: ACK (issue-21) ----------------
    dict(
        id="M83",
        f=MACH,
        loc="recordAckAt g1 — acks are ingested only while streaming",
        old="      s.phase == Streaming,\n      not(ackIsAboveHead(pn, wire)),",
        new="      s.phase != Disconnected,\n      not(ackIsAboveHead(pn, wire)),",
        exp="(pre-registered miss) AckedOffset outside Streaming is unconstrained",
    ),
    dict(
        id="M84",
        f=MACH,
        loc="recordAckAt g2 — the head validation gates the write path",
        old="      not(ackIsAboveHead(pn, wire)),\n      keepNodes,",
        new="      keepNodes,",
        exp="inv_ack_never_above_live_head (defects.ackAboveHead)",
    ),
    dict(
        id="M85",
        f=MACH,
        loc="recordAckAt — the accepted ack is written",
        old="      sessions' = sessions.set(sid, sPost),",
        new="      keepSessions,",
        exp="ackAboveLiveHeadIgnoredTest (acked == 2)",
    ),
    dict(
        id="M86",
        f=MACH,
        loc="recordAckAt — the above-head ghost reads the post-state",
        old="        ackAboveHead: latch(defects.ackAboveHead, sPost.acked > pn.recv) },",
        new="        ackAboveHead: latch(defects.ackAboveHead, false) },",
        exp="(pre-registered miss) ghost self-mutation (M84/F47 are the behaviour rows)",
    ),
    dict(
        id="M87",
        f=MACH,
        loc="ignoreAckAt g2 — the ignore branch takes only above-head acks",
        old="      ackIsAboveHead(pn, wire),\n      nodes' = nodes.set(s.primary, { ...pn, acks_ignored: pn.acks_ignored + 1 }),",
        new="      nodes' = nodes.set(s.primary, { ...pn, acks_ignored: pn.acks_ignored + 1 }),",
        exp="ackAboveLiveHeadIgnoredTest (acks_ignored == 1 after an honest ack)",
    ),
    dict(
        id="M88",
        f=MACH,
        loc="ignoreAckAt — the ruled outcome is ignore, not clamp (issue-21)",
        old="    val sessionsPost = sessions\n    all {",
        new="    val sessionsPost = sessions.set(sid, { ...s, acked: pn.recv })\n    all {",
        exp="inv_ack_never_above_live_head (defects.ackWrittenOnIgnore)",
    ),
    dict(
        id="M89",
        f=MACH,
        loc="ignoreAckAt — the ignore is counted",
        old="      nodes' = nodes.set(s.primary, { ...pn, acks_ignored: pn.acks_ignored + 1 }),",
        new="      keepNodes,",
        exp="ackAboveLiveHeadIgnoredTest (acks_ignored == 1)",
    ),
    dict(
        id="M90",
        f=MACH,
        loc="ignoreAckAt — the ack-written ghost reads the post-state",
        old="          sessionsPost.get(sid).acked != s.acked) },",
        new="          false) },",
        exp="(pre-registered miss) ghost self-mutation (M88 is the behaviour row)",
    ),
    dict(
        id="M91",
        f=MACH,
        loc="ignoreAckAt — the ignored-ack coverage latch",
        old="      coverage' = { ...coverage, ackIgnored: latch(coverage.ackIgnored, true) },",
        new="      coverage' = { ...coverage, ackIgnored: latch(coverage.ackIgnored, false) },",
        exp="ackAboveLiveHeadIgnoredTest (coverage.ackIgnored)",
    ),
    # ---------------- machine: promotion ----------------
    dict(
        id="M92",
        f=MACH,
        loc="promoteAs g1 — only a replica is promoted",
        old="      nn.role == Replica,\n      ctl.next_gen <= FIRST_GEN + MAX_GENS,",
        new="      ctl.next_gen <= FIRST_GEN + MAX_GENS,",
        exp="inv_identity_pair_monotone (a primary re-promotes and rewinds)",
    ),
    dict(
        id="M93",
        f=MACH,
        loc="promoteAs — the promotion commits to the node",
        old="      nodes' = nodes.set(n, nPost),",
        new="      keepNodes,",
        exp="promotionMidSyncTest (role == Primary)",
    ),
    dict(
        id="M94",
        f=MACH,
        loc="promoteAs — the promoted node's replica-side sessions die",
        old="        if (s.replica == n) { ...s, phase: Disconnected } else s",
        new="        s",
        exp="inv_link_points_at_a_live_session (promotionMidSyncTest)",
    ),
    dict(
        id="M95",
        f=MACH,
        loc="promoteAs — the promotion consumes a generation",
        old="      ctl' = ctlNextD(0, 1, 1),",
        new="      ctl' = ctlNextD(0, 0, 1),",
        exp="inv_replids_distinct (two promotions mint the same generation)",
    ),
    dict(
        id="M96",
        f=MACH,
        loc="promoteAs — the torn-identity ghost is armed",
        old="        tornIdentity: latch(defects.tornIdentity, not(promotePairedOk(nn, nPost))) },",
        new="        tornIdentity: latch(defects.tornIdentity, false) },",
        exp="(pre-registered miss) ghost self-mutation (F51-F53 are the behaviour rows)",
    ),
    dict(
        id="M97",
        f=MACH,
        loc="promoteAs — the settle-discard coverage latch",
        old="        settleDiscardedFrames: latch(coverage.settleDiscardedFrames, nn.recv > nn.applied) },",
        new="        settleDiscardedFrames: latch(coverage.settleDiscardedFrames, true) },",
        exp="(pre-registered miss) over-latch with no negative assertion",
    ),
    # ---------------- machine: restart ----------------
    dict(
        id="M98",
        f=MACH,
        loc="restartNodeAs g1 — the restart subject is a primary",
        old="      nn.role == Primary,\n      keep <= nn.applied,",
        new="      keep <= nn.applied,",
        exp="inv_identity_pair_monotone / restartRefusesAheadReplicaTest",
    ),
    dict(
        id="M99",
        f=MACH,
        loc="restartNodeAs g2 — recovery never invents data (TR-021)",
        old="      keep <= nn.applied,\n      keptId or ctl.next_gen <= FIRST_GEN + MAX_GENS,",
        new="      keptId or ctl.next_gen <= FIRST_GEN + MAX_GENS,",
        exp="restartRefusesAheadReplicaTest (.fail() shape) / inv_applied_covered_by_data",
    ),
    dict(
        id="M100",
        f=MACH,
        loc="restartNodeAs — the recovered state commits",
        old="      nodes' = unlinkedFrom(nodes.set(n, nPost), n),",
        new="      nodes' = unlinkedFrom(nodes, n),",
        exp="uncleanRestartMintsFreshIdTest (replid changed)",
    ),
    dict(
        id="M101",
        f=MACH,
        loc="restartNodeAs — a reboot drops the session registry it owned",
        old="      sessions' = sessionsWithout(n),",
        new="      keepSessions,",
        exp="inv_link_points_at_a_live_session",
    ),
    dict(
        id="M102",
        f=MACH,
        loc="restartNodeAs — only a reminting restart consumes a generation",
        old="      ctl' = ctlNextD(0, if (keptId) 0 else 1, 1),",
        new="      ctl' = ctlNextD(0, 0, 1),",
        exp="inv_replids_distinct / inv_identity_pair_monotone",
    ),
    dict(
        id="M103",
        f=MACH,
        loc="restartNodeAs — the offset-pairing ghost is armed",
        old="        restartOffsetTorn: latch(defects.restartOffsetTorn, not(restartOffsetPairedOk(nPost))),",
        new="        restartOffsetTorn: latch(defects.restartOffsetTorn, false),",
        exp="(pre-registered miss) ghost self-mutation (F60-F63 are the behaviour rows)",
    ),
    dict(
        id="M104",
        f=MACH,
        loc="restartNodeAs — the remint-shift ghost is armed (issue-24 (a))",
        old="            not(nPost.replid2 == Some(nn.replid) and nPost.second_offset == keep)) },",
        new="            false) },",
        exp="(pre-registered miss) ghost self-mutation (F68/F69 are the behaviour rows)",
    ),
    dict(
        id="M105",
        f=MACH,
        loc="restartNodeAs — the remint coverage latch",
        old="        uncleanRestartReminted: latch(coverage.uncleanRestartReminted, not(keptId)) },",
        new="        uncleanRestartReminted: latch(coverage.uncleanRestartReminted, false) },",
        exp="uncleanRestartMintsFreshIdTest (coverage.uncleanRestartReminted)",
    ),
    # ---------------- machine: link lifecycle ----------------
    dict(
        id="M106",
        f=MACH,
        loc="dropLinkAt g2 — a link is dropped only by its own holder",
        old="      s.phase == Streaming,\n      linkIs(rn, sid),\n      nodes' = nodes.set(s.replica, { ...rn, link: None }),",
        new="      s.phase == Streaming,\n      nodes' = nodes.set(s.replica, { ...rn, link: None }),",
        exp="(pre-registered miss) clearing a foreign link only removes behaviour",
    ),
    dict(
        id="M107",
        f=MACH,
        loc="dropLinkAt — the corpse is created replica-side only",
        old="      nodes' = nodes.set(s.replica, { ...rn, link: None }),\n      keepSessions,\n      keepCtl,\n      keepDefects,\n      coverage' = { ...coverage, corpseSession: latch(coverage.corpseSession, true) },",
        new="      nodes' = nodes.set(s.replica, { ...rn, link: None }),\n      sessions' = sessions.set(sid, { ...s, phase: Disconnected }),\n      keepCtl,\n      keepDefects,\n      coverage' = { ...coverage, corpseSession: latch(coverage.corpseSession, true) },",
        exp="supersededPredecessorTest (the corpse must survive to be superseded)",
    ),
    dict(
        id="M108",
        f=MACH,
        loc="dropLinkAt — the corpse coverage latch",
        old="      coverage' = { ...coverage, corpseSession: latch(coverage.corpseSession, true) },",
        new="      coverage' = { ...coverage, corpseSession: latch(coverage.corpseSession, false) },",
        exp="(pre-registered miss) witness-only latch with no test assertion",
    ),
    dict(
        id="M109",
        f=MACH,
        loc="endSessionAt — the ending session clears only its own holder's link",
        old="        .set(s.replica, if (linkIs(rn, sid)) { ...rn, link: None } else rn)",
        new="        .set(s.replica, { ...rn, link: None })",
        exp="(pre-registered miss) clearing a foreign link only removes behaviour",
    ),
    dict(
        id="M110",
        f=MACH,
        loc="endSessionAt — a streaming teardown records a graceful departure",
        old="          if (s.phase == Streaming) { ...pn, last_departure: Some(Graceful) } else pn),",
        new="          pn),",
        exp="(pre-registered miss) last_departure is the feed-gate model's subject",
    ),
    dict(
        id="M111",
        f=MACH,
        loc="endSessionAt — the session slot is freed",
        old="      sessions' = sessions.set(sid, { ...s, phase: Disconnected }),\n      keepCtl,\n      keepDefects,\n      keepCoverage,",
        new="      keepSessions,\n      keepCtl,\n      keepDefects,\n      keepCoverage,",
        exp="inv_link_points_at_a_live_session / supersededPredecessorTest",
    ),
    # ---------------- machine: step wiring (A57/A58 class) ----------------
    dict(
        id="M112",
        f=MACH,
        loc="step — the apply arm is reachable",
        old="    applyStep,\n    ackStep,",
        new="    ackStep,",
        exp="(pre-registered miss) witness-zero only; documented detection hole",
    ),
    dict(
        id="M113",
        f=MACH,
        loc="step — the abandon arm is reachable",
        old="    abandonStep,\n    receiveStep,",
        new="    receiveStep,",
        exp="(pre-registered miss) witness-zero only; documented detection hole",
    ),
    dict(
        id="M114",
        f=MACH,
        loc="teardownStep — the restart arm is reachable",
        old="    any { restartStep, endSessionStep },",
        new="    any { endSessionStep },",
        exp="(pre-registered miss) witness-zero only; documented detection hole",
    ),
    # ---------------- types: sizing / sentinels ----------------
    dict(
        id="T01",
        f=TYPES,
        loc="NO_WINDOW — the absent-window sentinel is out of band",
        old="  pure val NO_WINDOW: Offset = -1",
        new="  pure val NO_WINDOW: Offset = 0",
        exp="inv_failover_window_whole (offset 0 is a legal boundary)",
    ),
    dict(
        id="T02",
        f=TYPES,
        loc="UNARMED — the unarmed-floor sentinel is out of band",
        old="  pure val UNARMED: Offset = -1",
        new="  pure val UNARMED: Offset = 0",
        exp="backlogEvictionForcesFullResyncTest / inv_backlog_floor_sound",
    ),
    dict(
        id="T03",
        f=TYPES,
        loc="NO_HISTORY — the no-history generation is distinct from a real one",
        old="  pure val NO_HISTORY: Gen = 0",
        new="  pure val NO_HISTORY: Gen = 1",
        exp="happyFullSyncTest (a virgin replica matches FIRST_GEN)",
    ),
    dict(
        id="T04",
        f=TYPES,
        loc="FIRST_GEN — the first real generation is not the no-history sentinel",
        old="  pure val FIRST_GEN: Gen = 1",
        new="  pure val FIRST_GEN: Gen = 0",
        exp="happyFullSyncTest / inv_partial_grant_sound",
    ),
    dict(
        id="T05",
        f=TYPES,
        loc="BACKLOG_CAP — the backlog is finite (sizing knob)",
        old="  pure val BACKLOG_CAP: int = 1",
        new="  pure val BACKLOG_CAP: int = 4",
        exp="backlogEvictionForcesFullResyncTest (eviction unreachable)",
    ),
    dict(
        id="T06",
        f=TYPES,
        loc="MAX_WRITES / MAX_GENS / MAX_DISRUPTS — bounded-exploration knobs",
        old="  pure val MAX_WRITES: int = 4",
        new="  pure val MAX_WRITES: int = 8",
        exp="(pre-registered N/A) sizing knob, no semantics",
    ),
    # ---------------- main: invariant clause tightness ----------------
    dict(
        id="I01",
        f=MAIN,
        loc="inv_no_acked_write_lost — the antecedent restricts to a shared id",
        old="      (s.phase == Streaming and r.replid == p.replid)",
        new="      (s.phase == Streaming)",
        exp="violated by the unmutated model (clause is load-bearing, not slack)",
    ),
    dict(
        id="I02",
        f=MAIN,
        loc="inv_no_acked_write_lost — agreement is checked to the applied offset",
        old="        implies prefixAgrees(r.data, p.data, r.applied)",
        new="        implies prefixAgrees(r.data, p.data, r.data.length())",
        exp="violated by the unmutated model (the overshipped tail is legal)",
    ),
    dict(
        id="I03",
        f=MAIN,
        loc="inv_applied_covered_by_data — applied never exceeds the dataset",
        old="    NODES.forall(n => nodes.get(n).applied <= nodes.get(n).data.length())",
        new="    NODES.forall(n => nodes.get(n).applied == nodes.get(n).data.length())",
        exp="violated by the unmutated model (the overshipped tail is legal)",
    ),
    dict(
        id="I04",
        f=MAIN,
        loc="inv_offsets_ordered — applied never exceeds recv",
        old="    NODES.forall(n => nodes.get(n).applied <= nodes.get(n).recv)",
        new="    NODES.forall(n => nodes.get(n).applied == nodes.get(n).recv)",
        exp="violated by the unmutated model (a received-but-unapplied tail is legal)",
    ),
    dict(
        id="I05",
        f=MAIN,
        loc="inv_second_offset_not_above_live — the primary-role antecedent",
        old="      (s.role == Primary and s.second_offset != NO_WINDOW)",
        new="      (s.second_offset != NO_WINDOW)",
        exp="(pre-registered miss) → strengthen permanently if green",
    ),
    dict(
        id="I06",
        f=MAIN,
        loc="inv_second_offset_not_above_live — the boundary is inclusive",
        old="        implies s.second_offset <= s.recv",
        new="        implies s.second_offset < s.recv",
        exp="violated by the unmutated model (promotion freezes at exactly recv)",
    ),
    dict(
        id="I07",
        f=MAIN,
        loc="inv_backlog_floor_sound — an armed floor is inside the history",
        old="      (s.floor != UNARMED) implies (s.floor >= 0 and s.floor <= s.recv)",
        new="      (s.floor != UNARMED) implies (s.floor > 0 and s.floor <= s.recv)",
        exp="violated by the unmutated model (the first push arms the floor at 0)",
    ),
    dict(
        id="I08",
        f=MAIN,
        loc="inv_one_session_per_announced_identity — dedup applies to announced peers only",
        old="        sa.identity != None,",
        new="        true,",
        exp="violated by the unmutated model (unannounced peers are dedup-exempt)",
    ),
    dict(
        id="I09",
        f=MAIN,
        loc="inv_identity_pair_monotone — the antecedent needs a primary predecessor",
        old="      (prev.primary and cur.role == Primary)",
        new="      (cur.role == Primary)",
        exp="violated by the unmutated model (a promotion's predecessor was a replica)",
    ),
    dict(
        id="I10",
        f=MAIN,
        loc="inv_identity_pair_monotone — the antecedent needs a primary successor",
        old="      (prev.primary and cur.role == Primary)",
        new="      (prev.primary)",
        exp="(pre-registered miss) no demotion transition exists in the model",
    ),
    dict(
        id="I11",
        f=MAIN,
        loc="inv_link_points_at_a_live_session — the session must belong to the holder",
        old="      s.phase != Disconnected and s.replica == n",
        new="      s.phase != Disconnected",
        exp="(pre-registered miss) → keep as a tightness record if green",
    ),
]
