version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "ci"

  - package-ecosystem: docker
    directory: /frogdb-server/docker
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps"

  - package-ecosystem: docker
    directory: /.github/runner
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"

  - package-ecosystem: npm
    directory: /frogdb-server/crates/debug
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"

  - package-ecosystem: pip
    directory: /.github/workflows/workflow_gen
    schedule:
      interval: weekly
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
