//! Typed metrics infrastructure.
//!
//! This module provides the foundation for compile-time type-safe metrics:
//! - `MetricType` enum for counter/gauge/histogram
//! - `MetricDefinition` for runtime introspection
//!
//! The actual metric types are generated by the `define_metrics!` macro
//! in the `definitions` module.

use std::fmt;

/// Type of a metric.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MetricType {
    /// A monotonically increasing counter.
    Counter,
    /// A value that can go up and down.
    Gauge,
    /// A distribution of values (latency, sizes, etc.).
    Histogram,
}

impl MetricType {
    /// Get the string representation of this metric type.
    pub const fn as_str(&self) -> &'static str {
        match self {
            MetricType::Counter => "counter",
            MetricType::Gauge => "gauge",
            MetricType::Histogram => "histogram",
        }
    }
}

impl fmt::Display for MetricType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Definition of a metric for runtime introspection.
///
/// This is used by the dashboard generator and metrics verification tests.
#[derive(Debug, Clone, Copy)]
pub struct MetricDefinition {
    /// The Prometheus metric name (e.g., "frogdb_commands_total").
    pub name: &'static str,
    /// Help text describing the metric.
    pub help: &'static str,
    /// The type of metric.
    pub metric_type: MetricType,
    /// Label names for this metric.
    pub labels: &'static [&'static str],
}

impl MetricDefinition {
    /// Get the category prefix from the metric name.
    ///
    /// For "frogdb_commands_total", returns "commands".
    pub fn category(&self) -> &str {
        // Skip "frogdb_" prefix
        let name = self.name.strip_prefix("frogdb_").unwrap_or(self.name);
        // Take until the next underscore
        name.split('_').next().unwrap_or(name)
    }
}
