# FrogDB Helm Values Template
# Generated by Terraform

replicaCount: ${replica_count}

image:
  repository: "${image_repository}"
  tag: "${image_tag}"
  pullPolicy: IfNotPresent

cluster:
  enabled: ${cluster_enabled}
  busPort: 16379
  dataDir: /data/cluster
  electionTimeoutMs: 1000
  heartbeatIntervalMs: 250
  autoFailover: true

frogdb:
  port: 6379
  numShards: 4
  logging:
    level: info
    format: json
  persistence:
    enabled: true
    dataDir: /data
    durabilityMode: periodic
    syncIntervalMs: 1000
  metrics:
    enabled: true
    port: 9090
  admin:
    enabled: true
    port: 6380

resources:
  limits:
    cpu: "${cpu_limit}"
    memory: "${memory_limit}"
  requests:
    cpu: "${cpu_request}"
    memory: "${memory_request}"

persistence:
  enabled: true
  storageClass: "${storage_class}"
  size: "${storage_size}"
  accessModes:
    - ReadWriteOnce

podDisruptionBudget:
  enabled: ${cluster_enabled}
  minAvailable: ${ cluster_enabled ? max(1, floor(replica_count / 2) + 1) : 1 }

serviceMonitor:
  enabled: ${service_monitor_enabled}
  interval: 30s
  scrapeTimeout: 10s

%{ if cluster_enabled ~}
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - frogdb
          topologyKey: kubernetes.io/hostname
%{ endif ~}
