apiVersion: v1
kind: Service
metadata:
  name: {{ include "frogdb.fullname" . }}
  labels:
    {{- include "frogdb.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
    {{- if .Values.frogdb.metrics.enabled }}
    - port: {{ .Values.frogdb.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
    {{- if .Values.frogdb.admin.enabled }}
    - port: {{ .Values.frogdb.admin.port }}
      targetPort: admin
      protocol: TCP
      name: admin
    {{- end }}
  selector:
    {{- include "frogdb.selectorLabels" . | nindent 4 }}
