#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate the website's Specifications section from `specs/*.md`.

`specs/<area>.md` is the single source of truth (see
`.scratch/formal-spec/2026-08-12-formal-state-spec-design.md` §6). Each spec is
copied into the Starlight content collection with frontmatter injected, its H1
consumed as the page title, and its repo-relative links rewritten:

  * a sibling spec link (`replication.md#fm-replication-001`) becomes a site
    route (`/specifications/replication/#fm-replication-001`);
  * every other repo-relative link becomes a GitHub blob URL, because the
    target — an issue under `.scratch/`, a Rust source file — is not published
    and would otherwise be a dead link in the built site.

Usage:
    uv run website/scripts/spec-gen.py            # generate
    uv run website/scripts/spec-gen.py --check    # verify (CI)
"""

from __future__ import annotations

import argparse
import posixpath
import re
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
SPEC_DIR = REPO_ROOT / "specs"
OUT_DIR = REPO_ROOT / "website" / "src" / "content" / "docs" / "specifications"
GITHUB_BLOB = "https://github.com/frogdb/frogdb/blob/main/"
GENERATED = "<!-- DO NOT EDIT — auto-generated by: just spec-gen (source: {source}) -->"

# Sidebar order, the display name, and the one-line blurb per area. A spec
# with no entry here is an error rather than a default: order, display name,
# and blurb are editorial choices the generator cannot infer, and a new area
# should be introduced deliberately.
AREAS: dict[str, tuple[int, str, str]] = {
    "cluster": (1, "Cluster", "Cluster topology, slot ownership, migration, and failover."),
    "replication": (
        2,
        "Replication",
        "Replication sessions, full sync, offsets, and acknowledgement.",
    ),
    "persistence": (
        3,
        "Persistence",
        "WAL, checkpoints, recovery, and durability acknowledgement.",
    ),
    "txn": (4, "Transactions", "MULTI/EXEC transactions, WATCH, and script atomicity."),
    "vll": (5, "VLL", "Very Lightweight Locking: acquisition, continuation, and drain."),
    "blocking": (6, "Blocking", "Blocking commands: waits, wakeups, and disconnect handling."),
}

# `](target)` or `](target "title")`
LINK_RE = re.compile(r"\]\(([^)\s]+)((?:\s+\"[^\"]*\")?)\)")

# Reference-style link definitions: `[label]: target` (optionally `"title"`),
# line-anchored per CommonMark, with up to 3 leading spaces of indent.
REF_LINK_RE = re.compile(r'^( {0,3})\[([^\]]+)\]:\s*(\S+)((?:\s+"[^"]*")?)\s*$', re.MULTILINE)

# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def rewrite_link(target: str, *, spec_name: str) -> str:
    """A spec's link target, as the published page should carry it."""
    if target.startswith(("http://", "https://", "mailto:", "#")):
        return target
    path, sep, anchor = target.partition("#")
    fragment = f"#{anchor}" if sep else ""
    if not path:
        return target
    if path.endswith(".md") and "/" not in path and Path(path).stem in AREAS:
        return f"/specifications/{Path(path).stem}/{fragment}"
    # Anything else is repo-relative from `specs/` and is not published.
    normalized = posixpath.normpath(posixpath.join("specs", path))
    if normalized == ".." or normalized.startswith("../"):
        sys.exit(f"spec-gen: {spec_name} link target {path!r} escapes the repo root")
    return GITHUB_BLOB + normalized + fragment


def render(spec: Path) -> str:
    order, _display_name, blurb = AREAS[spec.stem]
    lines = spec.read_text().splitlines()
    if not lines or not lines[0].startswith("# "):
        sys.exit(f"spec-gen: {spec.name} does not start with an H1 title")
    title = lines[0].removeprefix("# ").strip().replace('"', "'")
    body = "\n".join(lines[1:]).lstrip("\n")
    body = LINK_RE.sub(
        lambda m: f"]({rewrite_link(m.group(1), spec_name=spec.name)}{m.group(2)})", body
    )
    body = REF_LINK_RE.sub(
        lambda m: (
            f"{m.group(1)}[{m.group(2)}]: "
            f"{rewrite_link(m.group(3), spec_name=spec.name)}{m.group(4)}"
        ),
        body,
    )
    front = "\n".join(
        [
            "---",
            f'title: "{title}"',
            f'description: "{blurb}"',
            "sidebar:",
            f"  order: {order}",
            "---",
            GENERATED.format(source=f"specs/{spec.name}"),
            "",
        ]
    )
    return f"{front}\n{body.rstrip()}\n"


def render_index(specs: list[Path]) -> str:
    rows = "\n".join(
        f"| [{AREAS[spec.stem][1]}](/specifications/{spec.stem}/) | {AREAS[spec.stem][2]} |"
        for spec in specs
    )
    return "\n".join(
        [
            "---",
            'title: "Specifications"',
            "description: \"The authoritative, lint-enforced specification of FrogDB's "
            'state and behavior, one document per area."',
            "sidebar:",
            "  order: 0",
            "---",
            GENERATED.format(source="specs/"),
            "",
            "These documents are the authority for FrogDB's behavior: each row states a rule",
            "and names the tests that force it. They are generated from the repository's",
            "`specs/` directory, and a lint checks in both directions that every row names a",
            "test and every tagged test names a row — a rule nothing forces is a gap, not a",
            "claim.",
            "",
            "| Area | Scope |",
            "|---|---|",
            rows,
            "",
        ]
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="verify the generated pages are up to date instead of writing them",
    )
    args = ap.parse_args()

    specs = sorted(SPEC_DIR.glob("*.md"))
    if not specs:
        print(f"spec-gen: no specs under {SPEC_DIR}", file=sys.stderr)
        return 1
    unknown = [spec.stem for spec in specs if spec.stem not in AREAS]
    if unknown:
        print(
            f"spec-gen: no AREAS entry for {', '.join(sorted(unknown))} — give the new "
            "area a sidebar order and a one-line scope blurb in spec-gen.py",
            file=sys.stderr,
        )
        return 1

    pages = {f"{spec.stem}.md": render(spec) for spec in specs}
    pages["index.md"] = render_index(specs)
    existing = {path.name: path.read_text() for path in sorted(OUT_DIR.glob("*.md"))}

    if args.check:
        stale = sorted(set(existing) - set(pages))
        missing = sorted(set(pages) - set(existing))
        changed = sorted(
            name for name in pages if name in existing and existing[name] != pages[name]
        )
        if stale or missing or changed:
            for name in missing:
                print(f"spec-gen: missing generated page {name}", file=sys.stderr)
            for name in changed:
                print(f"spec-gen: {name} is out of date", file=sys.stderr)
            for name in stale:
                print(f"spec-gen: {name} has no source spec", file=sys.stderr)
            print("spec-gen: run `just spec-gen`", file=sys.stderr)
            return 1
        print(f"spec-gen: {len(pages)} generated pages are up to date")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name in sorted(set(existing) - set(pages)):
        (OUT_DIR / name).unlink()
    for name, text in pages.items():
        (OUT_DIR / name).write_text(text)
    print(f"spec-gen: wrote {len(pages)} pages to {OUT_DIR.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
