#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Vendor the upstream Redis command list for the command-matrix join.

Fetches `src/commands/*.json` from the `redis/redis` GitHub repo at the tag
matching `REDIS_COMPAT_TARGET` (the single source of truth in
`frogdb-server/crates/types/src/redis_version.rs`) and writes a trimmed,
diff-stable `website/src/data/redis-commands-8x.json` containing just the
fields `matrix-gen.py` needs to join against the FrogDB command registry:
name, group, and since-version.

Unlike the other `website/src/data/*.json` files, this one is NOT
regenerated on every `just docs-build` — it's a point-in-time vendored
snapshot, network access to GitHub is required to refresh it, and upstream
Redis only adds/renames commands a few times a year. `matrix-gen.py` checks
the vendored `redis_version` against `REDIS_COMPAT_TARGET` on every run and
fails loudly if they've drifted, so a version bump can't silently go
un-vendored.

Subcommands (upstream files with a `container` key, e.g. `ACL CAT`) are
skipped: FrogDB's registry dispatches subcommands internally and only
exposes the container command (`ACL`, `CONFIG`, ...) as a registry entry,
so joining against subcommand names would never match anything and would
just inflate the "unsupported" column with phantom rows.

Usage:
    uv run website/scripts/vendor-redis-commands.py
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.request
from datetime import date
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "website" / "src" / "data" / "redis-commands-8x.json"
REDIS_VERSION_PATH = REPO_ROOT / "frogdb-server" / "crates" / "types" / "src" / "redis_version.rs"

REDIS_COMPAT_TARGET_RE = re.compile(r'pub const REDIS_COMPAT_TARGET:\s*&str\s*=\s*"([^"]+)"')

GITHUB_API = "https://api.github.com/repos/redis/redis/contents/src/commands"
GITHUB_TREE = "https://github.com/redis/redis/tree"


def get_redis_compat_target() -> str:
    """Read REDIS_COMPAT_TARGET from frogdb-types, the single source of truth."""
    content = REDIS_VERSION_PATH.read_text()
    match = REDIS_COMPAT_TARGET_RE.search(content)
    if not match:
        raise SystemExit(f"Could not find REDIS_COMPAT_TARGET in {REDIS_VERSION_PATH}")
    return match.group(1)


def fetch_json(url: str) -> object:
    request = urllib.request.Request(url, headers={"User-Agent": "frogdb-docs-gen"})
    with urllib.request.urlopen(request) as response:  # noqa: S310 (pinned https:// host)
        return json.load(response)


def vendor(redis_version: str) -> dict:
    """Fetch and filter the top-level command list for `redis_version`."""
    try:
        listing = fetch_json(f"{GITHUB_API}?ref={redis_version}")
    except urllib.error.HTTPError as exc:
        raise SystemExit(
            f"Failed to list src/commands at redis/redis@{redis_version}: {exc}. "
            "Does that tag exist upstream?"
        ) from exc

    commands: dict[str, dict] = {}
    for entry in listing:
        name = entry.get("name", "")
        if not name.endswith(".json"):
            continue
        data = fetch_json(entry["download_url"])
        for cmd_name, meta in data.items():
            if "container" in meta:
                continue  # subcommand (e.g. "ACL CAT") — not a registry entry
            commands[cmd_name] = {
                "name": cmd_name,
                "group": meta.get("group", "").replace("_", "-"),
                "since": meta.get("since", ""),
            }

    sorted_commands = [commands[name] for name in sorted(commands)]

    return {
        "_vendored": {
            "warning": "DO NOT EDIT — vendored from upstream Redis, not regenerated by "
            "just docs-build",
            "source": f"{GITHUB_TREE}/{redis_version}/src/commands",
            "redis_version": redis_version,
            "retrieved": date.today().isoformat(),
            "regenerate": "uv run website/scripts/vendor-redis-commands.py",
        },
        "count": len(sorted_commands),
        "commands": sorted_commands,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Vendor the upstream Redis command list (name, group, since) "
        "pinned to REDIS_COMPAT_TARGET."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Output path for the vendored JSON file",
    )
    args = parser.parse_args()

    redis_version = get_redis_compat_target()
    print(f"Vendoring redis/redis@{redis_version} src/commands/ ...")
    data = vendor(redis_version)
    generated_json = json.dumps(data, indent=2, ensure_ascii=False) + "\n"

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated_json)
    print(f"Vendored {data['count']} commands to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
