#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Codegen: vendored upstream command JSON -> a checked-in Rust data module.

Reads the two point-in-time snapshots `website/scripts/vendor-redis-commands.py`
vendors —

    website/src/data/redis-commands-8x.json         (redis/redis core)
    website/src/data/redis-module-commands-8x.json  (bundled module families)

— and emits

    frogdb-server/crates/commands/src/upstream/generated.rs

as `&'static` slices of the plain-data types hand-maintained next door in
`upstream/mod.rs`. No serde at runtime, no allocation at startup: the whole
snapshot is rodata the linker places once.

Why a separate generator rather than an arm of `docs-gen`: `docs-gen` runs the
other way round (it links `frogdb-server` and dumps the *live* registry to
JSON), so making it also emit a source file that `frogdb-server` compiles would
put the workspace in a bootstrap cycle. This one only reads JSON and writes
text, so it stays a `uv run --script` sibling of the other repo generators.

Feature gating: each module family's table is wrapped in the cargo features
that compile that family's commands into the registry, so a `core-profile`
build carries only the core table plus the always-registered families. A
family whose feature is off still has a `ModuleFamilyTable` (so the pin stays
reportable) with an empty command slice. FAMILY_FEATURES below is the mapping;
an upstream family missing from it is a hard error rather than a silent
ungated table.

Usage:
    uv run scripts/gen-command-metadata.py            # just command-metadata-gen
    uv run scripts/gen-command-metadata.py --check    # just command-metadata-gen-check
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "website" / "src" / "data"
CORE_INPUT = DATA_DIR / "redis-commands-8x.json"
MODULE_INPUT = DATA_DIR / "redis-module-commands-8x.json"
OUTPUT = REPO_ROOT / "frogdb-server" / "crates" / "commands" / "src" / "upstream" / "generated.rs"

# Upstream family -> the `frogdb-commands` cargo features that register its
# commands. An empty tuple means "always compiled": the server crate registers
# `FT.*` unconditionally, so gating the RediSearch table would hide rows for
# commands that are live in a `core-profile` build.
FAMILY_FEATURES: dict[str, tuple[str, ...]] = {
    "RediSearch": (),
    "RedisBloom": ("bloom", "cuckoo", "cms", "topk", "tdigest"),
    "RedisJSON": ("json",),
    "RedisTimeSeries": ("timeseries",),
    "VectorSets": ("vectorset",),
}

HEADER = """\
//! Vendored upstream command metadata — **DO NOT EDIT**.
//!
//! Generated by `uv run scripts/gen-command-metadata.py` (`just
//! command-metadata-gen`) from the vendored snapshots
//! `website/src/data/redis-commands-8x.json` and
//! `website/src/data/redis-module-commands-8x.json`, which
//! `website/scripts/vendor-redis-commands.py` fetches from
//! `redis/redis@{version}` and the module repos that release pins.
//!
//! `just command-metadata-gen-check` fails if this file has drifted from the
//! snapshots. To refresh the snapshots themselves (network access required),
//! run `just redis-commands-vendor` after bumping `REDIS_COMPAT_TARGET`.
//!
//! Types, and the meaning of an absent field, live in the hand-maintained
//! [`super`] module.

use super::{{
    BeginSearch, FindKeys, HistoryEntry, MetadataSource, ModuleFamilyTable, UpstreamArg,
    UpstreamCommand, UpstreamKeySpec,
}};

/// The `REDIS_COMPAT_TARGET` the snapshots were vendored at.
pub const REDIS_VERSION: &str = {version_lit};
"""


def rust_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def rust_opt_str(value: str | None) -> str:
    return f"Some({rust_str(value)})" if value is not None else "None"


def rust_str_slice(values: list[str]) -> str:
    return "&[" + ", ".join(rust_str(v) for v in values) + "]"


def emit_begin_search(spec: dict) -> str:
    if "index" in spec:
        return f"BeginSearch::Index {{ pos: {int(spec['index']['pos'])} }}"
    if "keyword" in spec:
        kw = spec["keyword"]
        return (
            f"BeginSearch::Keyword {{ keyword: {rust_str(kw['keyword'])}, "
            f"startfrom: {int(kw['startfrom'])} }}"
        )
    if "unknown" in spec:
        return "BeginSearch::Unknown"
    raise SystemExit(f"unknown begin_search shape: {spec!r}")


def emit_find_keys(spec: dict) -> str:
    if "range" in spec:
        r = spec["range"]
        return (
            f"FindKeys::Range {{ lastkey: {int(r['lastkey'])}, step: {int(r['step'])}, "
            f"limit: {int(r['limit'])} }}"
        )
    if "keynum" in spec:
        k = spec["keynum"]
        return (
            f"FindKeys::Keynum {{ keynumidx: {int(k['keynumidx'])}, "
            f"firstkey: {int(k['firstkey'])}, step: {int(k['step'])} }}"
        )
    if "unknown" in spec:
        return "FindKeys::Unknown"
    raise SystemExit(f"unknown find_keys shape: {spec!r}")


def emit_key_specs(cmd: dict, publishes_key_specs: bool, indent: str) -> str:
    """`None` when the source publishes no key-spec data; `Some(&[])` when it
    does and this command has no keys (upstream omits the field either way, so
    the distinction comes from the source, not from the row)."""
    if not publishes_key_specs:
        return "None"
    specs = cmd.get("key_specs")
    if not specs:
        return "Some(&[])"
    pad = indent + "    "
    rows = []
    for spec in specs:
        rows.append(
            f"{pad}UpstreamKeySpec {{ notes: {rust_opt_str(spec.get('notes'))}, "
            f"flags: {rust_str_slice(spec.get('flags', []))}, "
            f"begin_search: {emit_begin_search(spec['begin_search'])}, "
            f"find_keys: {emit_find_keys(spec['find_keys'])} }},"
        )
    return "Some(&[\n" + "\n".join(rows) + f"\n{indent}])"


def emit_args(args: list[dict], indent: str) -> str:
    if not args:
        return "&[]"
    pad = indent + "    "
    rows = []
    for arg in args:
        # Core Redis spells the override `display`; the module repos spell it
        # `display_text`. Both mean the name `COMMAND DOCS` shows, and Redis's
        # own reply field is `display_text`, so they merge here.
        display = arg.get("display_text", arg.get("display"))
        children = emit_args(arg.get("arguments", []), pad + "    ")
        rows.append(
            f"{pad}UpstreamArg {{\n"
            f"{pad}    name: {rust_opt_str(arg.get('name'))},\n"
            f"{pad}    kind: {rust_opt_str(arg.get('type'))},\n"
            f"{pad}    token: {rust_opt_str(arg.get('token'))},\n"
            f"{pad}    display_text: {rust_opt_str(display)},\n"
            f"{pad}    since: {rust_opt_str(arg.get('since'))},\n"
            f"{pad}    deprecated_since: {rust_opt_str(arg.get('deprecated_since'))},\n"
            f"{pad}    key_spec_index: "
            + (f"Some({int(arg['key_spec_index'])}),\n" if "key_spec_index" in arg else "None,\n")
            + f"{pad}    optional: {str(bool(arg.get('optional', False))).lower()},\n"
            f"{pad}    multiple: {str(bool(arg.get('multiple', False))).lower()},\n"
            f"{pad}    multiple_token: "
            f"{str(bool(arg.get('multiple_token', False))).lower()},\n"
            f"{pad}    arguments: {children},\n"
            f"{pad}}},"
        )
    return "&[\n" + "\n".join(rows) + f"\n{indent}]"


def emit_history(history: list[list[str]], indent: str) -> str:
    if not history:
        return "&[]"
    pad = indent + "    "
    rows = [
        f"{pad}HistoryEntry {{ version: {rust_str(version)}, change: {rust_str(change)} }},"
        for version, change in history
    ]
    return "&[\n" + "\n".join(rows) + f"\n{indent}]"


def emit_command(cmd: dict, source: str, publishes_key_specs: bool, indent: str) -> str:
    pad = indent + "    "
    flags = cmd.get("command_flags")
    arity = cmd.get("arity")
    return (
        f"{indent}UpstreamCommand {{\n"
        f"{pad}name: {rust_str(cmd['name'])},\n"
        f"{pad}source: {source},\n"
        f"{pad}group: {rust_str(cmd.get('group', ''))},\n"
        f"{pad}since: {rust_str(cmd.get('since', ''))},\n"
        f"{pad}summary: {rust_str(cmd.get('summary', ''))},\n"
        f"{pad}complexity: {rust_opt_str(cmd.get('complexity'))},\n"
        f"{pad}doc_flags: {rust_str_slice(cmd.get('doc_flags', []))},\n"
        f"{pad}deprecated_since: {rust_opt_str(cmd.get('deprecated_since'))},\n"
        f"{pad}replaced_by: {rust_opt_str(cmd.get('replaced_by'))},\n"
        f"{pad}arity: "
        + (f"Some({int(arity)}),\n" if arity is not None else "None,\n")
        + f"{pad}command_flags: "
        + (f"Some({rust_str_slice(flags)}),\n" if flags is not None else "None,\n")
        + f"{pad}command_tips: {rust_str_slice(cmd.get('command_tips', []))},\n"
        + f"{pad}has_subcommands: {str(bool(cmd.get('has_subcommands'))).lower()},\n"
        + f"{pad}key_specs: {emit_key_specs(cmd, publishes_key_specs, pad)},\n"
        f"{pad}arguments: {emit_args(cmd.get('arguments', []), pad)},\n"
        f"{pad}history: {emit_history(cmd.get('history', []), pad)},\n"
        f"{indent}}},"
    )


def cfg_attr(features: tuple[str, ...], *, negate: bool = False) -> str | None:
    """The `#[cfg(...)]` attribute gating a family's table, or None if always on.

    Wrapped across lines when the one-liner would exceed rustfmt's 100-column
    limit: `#[rustfmt::skip]` covers the item it precedes, not the attributes
    stacked above it, so a long `cfg` would leave the generated file failing
    `cargo fmt --check`.
    """
    if not features:
        return None
    if len(features) == 1:
        inner = f'feature = "{features[0]}"'
    else:
        inner = "any(" + ", ".join(f'feature = "{f}"' for f in sorted(features)) + ")"
    attr = f"#[cfg(not({inner}))]" if negate else f"#[cfg({inner})]"
    if len(attr) <= 100:
        return attr
    body = ",\n".join(f'    feature = "{f}"' for f in sorted(features))
    if negate:
        return "#[cfg(not(any(\n" + body + "\n)))]"
    return "#[cfg(any(\n" + body + "\n))]"


def generate() -> str:
    core = json.loads(CORE_INPUT.read_text())
    modules = json.loads(MODULE_INPUT.read_text())

    version = core["_vendored"]["redis_version"]
    if modules["_vendored"]["redis_version"] != version:
        raise SystemExit(
            "vendored snapshots disagree on redis_version "
            f"({version} vs {modules['_vendored']['redis_version']}) — "
            "re-run `just redis-commands-vendor`"
        )

    out = [HEADER.format(version=version, version_lit=rust_str(version)).rstrip("\n")]

    out.append("")
    out.append(f"/// Every top-level `redis/redis@{version}` command, sorted by name.")
    out.append("#[rustfmt::skip]")
    out.append("pub static REDIS_COMMANDS: &[UpstreamCommand] = &[")
    for cmd in core["commands"]:
        out.append(emit_command(cmd, "MetadataSource::Redis", True, "    "))
    out.append("];")

    family_idents: list[tuple[dict, str, tuple[str, ...]]] = []
    for family in modules["families"]:
        name = family["family"]
        if name not in FAMILY_FEATURES:
            raise SystemExit(
                f"vendored module family {name!r} has no entry in FAMILY_FEATURES. "
                "Add its cargo features (or an empty tuple if it is always "
                "registered) before regenerating."
            )
        ident = "".join(ch for ch in name.upper() if ch.isalnum())
        family_idents.append((family, ident, FAMILY_FEATURES[name]))

    for family, ident, features in family_idents:
        gate = cfg_attr(features)
        containers = sorted({row["container"] for row in family.get("subcommands", [])})
        source = f"MetadataSource::Module({rust_str(family['family'])})"

        out.append("")
        out.append(
            f"/// `{family['family']}` commands, vendored from {family['repo']}@{family['tag']}."
        )
        if gate:
            out.append(gate)
        out.append("#[rustfmt::skip]")
        out.append(f"static {ident}_COMMANDS: &[UpstreamCommand] = &[")
        for cmd in family["commands"]:
            out.append(emit_command(cmd, source, False, "    "))
        out.append("];")

        if gate:
            out.append("")
            out.append(
                f"/// Empty stand-in when the `{family['family']}` family is not compiled in."
            )
            out.append(cfg_attr(features, negate=True))
            out.append(f"static {ident}_COMMANDS: &[UpstreamCommand] = &[];")

        out.append("")
        out.append(
            f"/// `{family['family']}` container commands documented only through "
            "their subcommands."
        )
        if gate:
            out.append(gate)
        out.append(f"static {ident}_CONTAINERS: &[&str] = {rust_str_slice(containers)};")
        if gate:
            out.append("")
            out.append(cfg_attr(features, negate=True))
            out.append(f"static {ident}_CONTAINERS: &[&str] = &[];")

    out.append("")
    out.append("/// Every bundled-module family, with the upstream pin it was vendored from.")
    out.append("///")
    out.append("/// A family whose cargo feature is off keeps its row — the pin stays")
    out.append("/// reportable — but carries no commands.")
    out.append("pub static MODULE_FAMILIES: &[ModuleFamilyTable] = &[")
    for family, ident, features in family_idents:
        out.append("    ModuleFamilyTable {")
        out.append(f"        family: {rust_str(family['family'])},")
        out.append(f"        repo: {rust_str(family['repo'])},")
        out.append(f"        tag: {rust_str(family['tag'])},")
        out.append(f"        features: {rust_str_slice(list(features))},")
        out.append(f"        commands: {ident}_COMMANDS,")
        out.append(f"        containers: {ident}_CONTAINERS,")
        out.append("    },")
    out.append("];")
    out.append("")

    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the checked-in upstream command-metadata Rust module "
        "from the vendored Redis/module command JSON."
    )
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in file drifted")
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()

    generated = generate()

    if args.check:
        if not args.output.exists():
            print(f"{args.output} is missing — run `just command-metadata-gen`.", file=sys.stderr)
            return 1
        if args.output.read_text() != generated:
            print(
                f"{args.output} is out of date — run `just command-metadata-gen`.",
                file=sys.stderr,
            )
            return 1
        print(f"{args.output.name} is up to date.")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated)
    print(f"Generated {args.output} ({len(generated):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
