use std::collections::BTreeMap;
use std::path::Path;

use anyhow::{Context, Result};
use serde::Serialize;

/// Result of config validation.
#[derive(Debug, Serialize)]
pub struct ValidationResult {
    pub valid: bool,
    pub errors: Vec<String>,
    pub warnings: Vec<String>,
    pub fields_parsed: usize,
}

/// A single diff entry between two configs.
#[derive(Debug, Serialize)]
pub struct DiffEntry {
    pub section: String,
    pub key: String,
    pub value_a: Option<String>,
    pub value_b: Option<String>,
}

/// Generate an annotated default TOML configuration.
pub fn generate_default_config(cluster: bool) -> String {
    let mut config = String::new();

    config.push_str("# FrogDB Configuration\n");
    config.push_str("# Generated by `frog config generate`\n\n");

    config.push_str("[server]\n");
    config.push_str("# Bind address for RESP protocol\n");
    config.push_str("bind = \"0.0.0.0\"\n");
    config.push_str("# RESP port\n");
    config.push_str("port = 6379\n");
    config.push_str("# Number of shards (set to number of CPU cores)\n");
    config.push_str("num_shards = 8\n");
    config.push_str("# Maximum number of client connections\n");
    config.push_str("max_clients = 10000\n");
    config.push_str("# TCP keepalive interval in seconds (0 = disabled)\n");
    config.push_str("tcp_keepalive = 300\n");
    config.push_str("# Connection timeout in seconds (0 = disabled)\n");
    config.push_str("timeout = 0\n");
    config.push_str("\n");

    config.push_str("[memory]\n");
    config.push_str("# Maximum memory limit (0 = no limit)\n");
    config.push_str("# Supports suffixes: KB, MB, GB\n");
    config.push_str("max_memory = 0\n");
    config.push_str("# Eviction policy when max_memory is reached\n");
    config.push_str("# Options: noeviction, allkeys-lru, volatile-lru, allkeys-random, volatile-random, volatile-ttl\n");
    config.push_str("maxmemory_policy = \"noeviction\"\n");
    config.push_str("\n");

    config.push_str("[persistence]\n");
    config.push_str("# Enable persistence\n");
    config.push_str("enabled = false\n");
    config.push_str("# Data directory for snapshots and WAL\n");
    config.push_str("data_dir = \"./data\"\n");
    config.push_str("# Durability mode: async, periodic, sync\n");
    config.push_str("durability_mode = \"periodic\"\n");
    config.push_str("# Snapshot interval in seconds\n");
    config.push_str("snapshot_interval = 3600\n");
    config.push_str("\n");

    config.push_str("[logging]\n");
    config.push_str("# Log level: trace, debug, info, warn, error\n");
    config.push_str("level = \"info\"\n");
    config.push_str("# Log format: text, json\n");
    config.push_str("format = \"text\"\n");
    config.push_str("\n");

    config.push_str("[admin]\n");
    config.push_str("# Enable admin HTTP API\n");
    if cluster {
        config.push_str("enabled = true\n");
    } else {
        config.push_str("enabled = false\n");
    }
    config.push_str("# Admin API port\n");
    config.push_str("port = 6380\n");
    config.push_str("\n");

    config.push_str("[metrics]\n");
    config.push_str("# Enable Prometheus metrics endpoint\n");
    config.push_str("enabled = true\n");
    config.push_str("# Metrics port\n");
    config.push_str("port = 9090\n");
    config.push_str("\n");

    config.push_str("[slowlog]\n");
    config.push_str("# Log commands slower than this (microseconds, 0 = disabled)\n");
    config.push_str("slower_than = 10000\n");
    config.push_str("# Maximum number of slow log entries\n");
    config.push_str("max_len = 128\n");
    config.push_str("\n");

    if cluster {
        config.push_str("[cluster]\n");
        config.push_str("# Enable cluster mode\n");
        config.push_str("enabled = true\n");
        config.push_str("# Cluster announce address (for NAT/container environments)\n");
        config.push_str("# announce_ip = \"10.0.0.1\"\n");
        config.push_str("# announce_port = 6379\n");
        config.push_str("\n");

        config.push_str("[cluster.raft]\n");
        config.push_str("# Raft heartbeat interval in milliseconds\n");
        config.push_str("heartbeat_interval = 150\n");
        config.push_str("# Raft election timeout range in milliseconds\n");
        config.push_str("election_timeout_min = 300\n");
        config.push_str("election_timeout_max = 500\n");
        config.push_str("\n");
    }

    config
}

/// Validate a TOML config file.
pub fn validate_config(path: &Path) -> Result<ValidationResult> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("failed to read config file: {}", path.display()))?;

    let mut errors = Vec::new();
    let mut warnings = Vec::new();
    let mut fields_parsed = 0;

    // Parse TOML
    let table: toml::Table = match content.parse() {
        Ok(t) => t,
        Err(e) => {
            errors.push(format!("TOML parse error: {e}"));
            return Ok(ValidationResult {
                valid: false,
                errors,
                warnings,
                fields_parsed: 0,
            });
        }
    };

    // Known sections and their known keys
    let known_sections: BTreeMap<&str, Vec<&str>> = BTreeMap::from([
        (
            "server",
            vec![
                "bind",
                "port",
                "num_shards",
                "max_clients",
                "tcp_keepalive",
                "timeout",
            ],
        ),
        (
            "memory",
            vec!["max_memory", "maxmemory_policy"],
        ),
        (
            "persistence",
            vec![
                "enabled",
                "data_dir",
                "durability_mode",
                "snapshot_interval",
            ],
        ),
        ("logging", vec!["level", "format"]),
        ("admin", vec!["enabled", "port"]),
        ("metrics", vec!["enabled", "port"]),
        ("slowlog", vec!["slower_than", "max_len"]),
        ("cluster", vec!["enabled", "announce_ip", "announce_port"]),
        (
            "cluster.raft",
            vec![
                "heartbeat_interval",
                "election_timeout_min",
                "election_timeout_max",
            ],
        ),
    ]);

    let valid_durability_modes = ["async", "periodic", "sync"];
    let valid_eviction_policies = [
        "noeviction",
        "allkeys-lru",
        "volatile-lru",
        "allkeys-random",
        "volatile-random",
        "volatile-ttl",
    ];
    let valid_log_levels = ["trace", "debug", "info", "warn", "error"];

    for (section_name, value) in &table {
        if let toml::Value::Table(section) = value {
            // Check for nested sections (e.g., cluster.raft)
            for (key, val) in section {
                if let toml::Value::Table(nested) = val {
                    let nested_name = format!("{section_name}.{key}");
                    if let Some(known_keys) = known_sections.get(nested_name.as_str()) {
                        for nested_key in nested.keys() {
                            fields_parsed += 1;
                            if !known_keys.contains(&nested_key.as_str()) {
                                warnings.push(format!(
                                    "unknown field '{nested_key}' in [{nested_name}]"
                                ));
                            }
                        }
                    } else {
                        warnings.push(format!("unknown section [{nested_name}]"));
                    }
                } else {
                    fields_parsed += 1;
                    if let Some(known_keys) = known_sections.get(section_name.as_str()) {
                        if !known_keys.contains(&key.as_str()) {
                            warnings.push(format!(
                                "unknown field '{key}' in [{section_name}]"
                            ));
                        }
                    }
                }
            }

            if !known_sections.contains_key(section_name.as_str()) {
                // Only warn if it's not a parent of a known nested section
                let is_parent = known_sections
                    .keys()
                    .any(|k| k.starts_with(&format!("{section_name}.")));
                if !is_parent {
                    warnings.push(format!("unknown section [{section_name}]"));
                }
            }
        }
    }

    // Semantic validation
    if let Some(toml::Value::Table(server)) = table.get("server") {
        if let Some(toml::Value::Integer(port)) = server.get("port") {
            if *port < 0 || *port > 65535 {
                errors.push(format!("server.port must be 0-65535, got {port}"));
            }
        }
    }

    if let Some(toml::Value::Table(persistence)) = table.get("persistence") {
        if let Some(toml::Value::Boolean(true)) = persistence.get("enabled") {
            if persistence.get("data_dir").is_none() {
                errors
                    .push("persistence.enabled = true requires persistence.data_dir".to_string());
            }
        }
        if let Some(toml::Value::String(mode)) = persistence.get("durability_mode") {
            if !valid_durability_modes.contains(&mode.as_str()) {
                errors.push(format!(
                    "persistence.durability_mode must be one of: {}",
                    valid_durability_modes.join(", ")
                ));
            }
        }
    }

    if let Some(toml::Value::Table(memory)) = table.get("memory") {
        if let Some(toml::Value::String(policy)) = memory.get("maxmemory_policy") {
            if !valid_eviction_policies.contains(&policy.as_str()) {
                errors.push(format!(
                    "memory.maxmemory_policy must be one of: {}",
                    valid_eviction_policies.join(", ")
                ));
            }
        }
    }

    if let Some(toml::Value::Table(logging)) = table.get("logging") {
        if let Some(toml::Value::String(level)) = logging.get("level") {
            if !valid_log_levels.contains(&level.as_str()) {
                errors.push(format!(
                    "logging.level must be one of: {}",
                    valid_log_levels.join(", ")
                ));
            }
        }
    }

    Ok(ValidationResult {
        valid: errors.is_empty(),
        errors,
        warnings,
        fields_parsed,
    })
}

/// Diff two config files, returning entries that differ.
pub fn diff_configs(path_a: &Path, path_b: &Path) -> Result<Vec<DiffEntry>> {
    let content_a = std::fs::read_to_string(path_a)
        .with_context(|| format!("failed to read: {}", path_a.display()))?;
    let content_b = std::fs::read_to_string(path_b)
        .with_context(|| format!("failed to read: {}", path_b.display()))?;

    let table_a: toml::Table = content_a
        .parse()
        .with_context(|| format!("failed to parse: {}", path_a.display()))?;
    let table_b: toml::Table = content_b
        .parse()
        .with_context(|| format!("failed to parse: {}", path_b.display()))?;

    let flat_a = flatten_toml(&table_a);
    let flat_b = flatten_toml(&table_b);

    let mut all_keys: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    all_keys.extend(flat_a.keys().cloned());
    all_keys.extend(flat_b.keys().cloned());

    let mut diffs = Vec::new();
    for key in all_keys {
        let val_a = flat_a.get(&key);
        let val_b = flat_b.get(&key);
        if val_a != val_b {
            let (section, field) = key.rsplit_once('.').unwrap_or(("", &key));
            diffs.push(DiffEntry {
                section: section.to_string(),
                key: field.to_string(),
                value_a: val_a.cloned(),
                value_b: val_b.cloned(),
            });
        }
    }

    Ok(diffs)
}

/// Flatten a TOML table into "section.key" = "value" pairs.
fn flatten_toml(table: &toml::Table) -> BTreeMap<String, String> {
    let mut result = BTreeMap::new();
    flatten_toml_inner(table, "", &mut result);
    result
}

fn flatten_toml_inner(table: &toml::Table, prefix: &str, result: &mut BTreeMap<String, String>) {
    for (key, value) in table {
        let full_key = if prefix.is_empty() {
            key.clone()
        } else {
            format!("{prefix}.{key}")
        };
        match value {
            toml::Value::Table(nested) => {
                flatten_toml_inner(nested, &full_key, result);
            }
            _ => {
                result.insert(full_key, format!("{value}"));
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_default_config_standalone() {
        let config = generate_default_config(false);
        assert!(config.contains("[server]"));
        assert!(config.contains("port = 6379"));
        assert!(!config.contains("[cluster]"));
        assert!(config.contains("admin"));
        // Standalone has admin disabled
        assert!(config.contains("enabled = false"));
    }

    #[test]
    fn test_generate_default_config_cluster() {
        let config = generate_default_config(true);
        assert!(config.contains("[cluster]"));
        assert!(config.contains("enabled = true"));
        assert!(config.contains("[cluster.raft]"));
    }

    #[test]
    fn test_validate_valid_config() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.toml");
        std::fs::write(
            &path,
            r#"
[server]
port = 6379
num_shards = 4

[persistence]
enabled = true
data_dir = "/data"
durability_mode = "periodic"
"#,
        )
        .unwrap();

        let result = validate_config(&path).unwrap();
        assert!(result.valid, "errors: {:?}", result.errors);
        assert!(result.errors.is_empty());
    }

    #[test]
    fn test_validate_bad_durability_mode() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.toml");
        std::fs::write(
            &path,
            r#"
[persistence]
durability_mode = "turbo"
"#,
        )
        .unwrap();

        let result = validate_config(&path).unwrap();
        assert!(!result.valid);
        assert!(result.errors.iter().any(|e| e.contains("durability_mode")));
    }

    #[test]
    fn test_validate_persistence_requires_data_dir() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.toml");
        std::fs::write(
            &path,
            r#"
[persistence]
enabled = true
"#,
        )
        .unwrap();

        let result = validate_config(&path).unwrap();
        assert!(!result.valid);
        assert!(result
            .errors
            .iter()
            .any(|e| e.contains("data_dir")));
    }

    #[test]
    fn test_validate_unknown_field_warning() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.toml");
        std::fs::write(
            &path,
            r#"
[server]
port = 6379
bogus_field = true
"#,
        )
        .unwrap();

        let result = validate_config(&path).unwrap();
        assert!(result.valid); // unknown fields are warnings, not errors
        assert!(result
            .warnings
            .iter()
            .any(|w| w.contains("bogus_field")));
    }

    #[test]
    fn test_diff_configs() {
        let dir = tempfile::tempdir().unwrap();
        let path_a = dir.path().join("a.toml");
        let path_b = dir.path().join("b.toml");
        std::fs::write(
            &path_a,
            r#"
[server]
port = 6379
num_shards = 8
"#,
        )
        .unwrap();
        std::fs::write(
            &path_b,
            r#"
[server]
port = 6380
num_shards = 8
"#,
        )
        .unwrap();

        let diffs = diff_configs(&path_a, &path_b).unwrap();
        assert_eq!(diffs.len(), 1);
        assert_eq!(diffs[0].key, "port");
        assert_eq!(diffs[0].value_a, Some("6379".to_string()));
        assert_eq!(diffs[0].value_b, Some("6380".to_string()));
    }
}
